razorpay/blade

- src/atoms/Flex/Flex.native.js
- src/atoms/Flex/Flex.web.js
- src/atoms/Flex/index.js
- src/atoms/Link/Link.native.js
- src/atoms/Link/Link.stories.js
- src/atoms/Link/Link.web.js
- src/atoms/Link/__tests__/Link.native.test.js
- src/atoms/Link/__tests__/__snapshots__/Link.native.test.js.snap
- src/atoms/Link/index.js
- storybook/native/main.js
This PR is chained to PR https://github.com/razorpay/blade/pull/15
> feat(link): add Link component

- now.json
> Revert "build(zeit): add now.json"

- jest.native.config.js
- src/_helpers/__tests__/theme.test.js
- src/_helpers/theme.js
- src/atoms/Button/Button.native.js
- src/atoms/Button/Button.stories.js
- src/atoms/Button/__tests__/Button.native.test.js
- src/atoms/Button/__tests__/__snapshots__/Button.native.test.js.snap
- src/tokens/spacings.js
- src/tokens/theme.web.js
Variations of Button for Design System(RN)
Current Dependencies:
1. `<Text />` from Design System
2. The color palette is being worked upon by the Design team.
> feat(Button): add Button component for react-native

- src/atoms/Button/__tests__/__snapshots__/Button.native.test.js.snap
- src/atoms/Checkbox/__tests__/__snapshots__/Checkbox.native.test.js.snap
- src/atoms/Flex/Flex.native.js
- src/atoms/Flex/__tests__/Flex.native.test.js
- src/atoms/Flex/__tests__/__snapshots__/Flex.native.test.js.snap
- src/atoms/Link/__tests__/__snapshots__/Link.native.test.js.snap
- src/atoms/Size/Size.native.js
- src/atoms/Size/__tests__/Size.native.test.js
- src/atoms/Size/__tests__/__snapshots__/Size.native.test.js.snap
- src/atoms/Space/Space.native.js
- src/atoms/Space/__tests__/Space.native.test.js
- src/atoms/Space/__tests__/__snapshots__/Space.native.test.js.snap
- src/atoms/TextInput/__tests__/__snapshots__/TextInput.native.test.js.snap
fixes nested styles when using flex/space/size and add test cases for the same.
> fix(flex/space/size): fixes nested styles when using flex/space/size on react-native

- src/atoms/Indicator/Indicator.native.js
- src/atoms/Indicator/Indicator.stories.js
- src/atoms/Indicator/Indicator.web.js
- src/atoms/Indicator/__tests__/Indicator.native.test.js
- src/atoms/Indicator/__tests__/__snapshots__/Indicator.native.test.js.snap
- src/atoms/Indicator/index.js
- storybook/native/main.js
Adds different variations of Indicator in RN for DS
> feat(indicator): Indicator for DS

- src/_helpers/theme.js
- src/atoms/Badge/Badge.native.js
- src/atoms/Badge/Badge.stories.js
- src/atoms/Badge/Badge.web.js
- src/atoms/Badge/__tests__/Badge.native.test.js
- src/atoms/Badge/__tests__/__snapshots__/Badge.native.test.js.snap
- src/atoms/Badge/index.js
- storybook/native/main.js
Adds Badges(pills/rectangular badges) for DS
> feat(badge): add badge for react-native

- src/atoms/Space/__tests__/Space.web.test.js
- src/atoms/Space/__tests__/__snapshots__/Space.web.test.js.snap
fix(space.web.test.js): Replace native render to react react render
> fix(Space): replace native renderer with react renderer for web

- src/molecules/Amount/Amount.native.js
Use the local intl library since different node environments
have different behaviors for intl functions
> fix(Amount/native): amount crash on different environments

- src/atoms/ScrollView/ScrollView.web.js
- src/atoms/ScrollView/__tests__/ScrollView.web.test.js
- src/atoms/ScrollView/__tests__/__snapshots__/ScrollView.web.test.js.snap
> feat(ScrollView/react): add component

- ios/Podfile.lock
- jest-setup.native.js
- jest.native.config.js
- package.json
- src/molecules/Tabs/TabBar.native.js
- src/molecules/Tabs/TabButton.native.js
- src/molecules/Tabs/Tabs.native.js
- src/molecules/Tabs/Tabs.stories.js
- src/molecules/Tabs/Tabs.web.js
- src/molecules/Tabs/__tests__/Tabs.native.test.js
- src/molecules/Tabs/__tests__/__snapshots__/Tabs.native.test.js.snap
- src/molecules/Tabs/index.js
- storybook/native/main.js
- yarn.lock
Co-authored-by: shridharbavannawar <shridhar.b@razorpay.com>
> feat(Tabs/native): create tabs component

- src/atoms/Checkbox/Checkbox.native.js
Updates the internal state when `checked` prop changes
> fix(native/Checkbox): modify bugs for controlled component

- src/molecules/Tabs/Tabs.native.js
- src/molecules/Tabs/__tests__/__snapshots__/Tabs.native.test.js.snap
onIndexChanged returns a function instead of a number while running it in jest. This commit ensures that tab is changed only if the callback index is a number.
> fix(native): fix snapshots for Tabs

- src/icons/Bell/Bell.native.js
- src/icons/Bell/Bell.web.js
- src/icons/Bell/index.js
- src/icons/Message/Message.native.js
- src/icons/Message/Message.web.js
- src/icons/Message/index.js
- src/icons/Share/Share.native.js
- src/icons/Share/Share.web.js
- src/icons/Share/index.js
- src/icons/index.js
> feat(icons): add bell, share and message icons

- src/atoms/Link/Link.native.js
- src/atoms/Link/__tests__/__snapshots__/Link.native.test.js.snap
Adds hitSlop(of 4 units) to Link to address issue listed in sheet(Point 71):
https://docs.google.com/spreadsheets/d/1xP5FHU3MugjxAttkxocD9Hm8O8Fa_zmxxEKLAEH1c68/edit#gid=0&fvid=1329607617
> refactor(native/Link): add hit-slop to Link

- src/atoms/Checkbox/Checkbox.native.js
- src/atoms/Checkbox/Checkbox.web.js
- src/atoms/Checkbox/__tests__/__snapshots__/Checkbox.web.test.js.snap
Slack Discussion: https://razorpay.slack.com/archives/CTM086NSF/p1603175140267000?thread_ts=1602750753.212400&cid=CTM086NSF
> feat(checkbox): update small size

- src/atoms/TextArea/__tests__/__snapshots__/TextArea.web.test.js.snap
- src/atoms/TextInput/TextInput.web.js
- src/atoms/TextInput/__tests__/__snapshots__/TextInput.web.test.js.snap
fixes: https://github.com/razorpay/blade/issues/224
> fix(TextInput/react): fix input overflowing parent

- packages/tools/figma-plugin-version-history/src/ui.vue
Also revoked the access to the old tokens.
> Removed figma file token and access token

- src/molecules/Tabs/TabBar.native.js
- src/molecules/Tabs/TabButton.native.js
- src/molecules/Tabs/Tabs.native.js
- src/molecules/Tabs/Tabs.stories.js
- src/molecules/Tabs/__tests__/__snapshots__/Tabs.native.test.js.snap
> feat(native/tabs): add scrollable tabs

- rfcs/2021-01-22-spatial-system-rfc.md
Here is the link to the [**updated RFC**](https://github.com/razorpay/blade/blob/add/rfc-spatial-system/rfcs/2021-01-22-spatial-system-rfc.md).
> docs(rfc): answer all the open question for spatial system

- src/icons/Plus/Plus.native.js
- src/icons/Plus/Plus.web.js
- src/icons/Plus/index.js
- src/icons/index.js
Adding plus icon, which needed in payout approve flow
> adding plus icon

- packages/blade-old/src/icons/Refresh/Refresh.native.js
- packages/blade-old/src/icons/Refresh/Refresh.web.js
- packages/blade-old/src/icons/Refresh/index.js
- packages/blade-old/src/icons/index.js
Added refetch icon needed for esign aadhar for payments app
> feat(icon): add refresh icon

- packages/blade/src/tokens/global/fontFamily.d.ts
- packages/blade/src/tokens/global/fontFamily.native.ts
- packages/blade/src/tokens/global/fontFamily.web.ts
- packages/blade/src/tokens/global/typography.ts
- packages/blade/src/tokens/theme/bankingTheme.ts
- packages/blade/src/tokens/theme/paymentTheme.ts
- packages/blade/src/tokens/theme/theme.d.ts
This PR adds typography tokens which accounts for font family, font size, font weight. Lineheight and Letterspacing tokens are yet to be worked upon by design so will add later in successive PR
> feat(theme): add typography scale

- .changeset/seven-paws-wait.md
Need to bump version for refetch icon
> refactor: bumping the version

- packages/blade/src/tokens/theme/bankingTheme.ts
This PR was opened by the Token Upload GitHub action. It updates source token files based on the payload from Figma Plugin.
> feat(tokens): add new tokens

- packages/blade/src/tokens/theme/theme.d.ts
This PR adds types for the tokens added recently in #301 and #302. Have not optimised the type a lot. Tried to keep it verbose since I don't have a way to abstract it rightly hence preferring to duplicate until the tokens reach a good state.
> fix(types): add types for new tokens

- .changeset/shiny-beans-guess.md
- packages/blade-old/src/molecules/BottomSheet/BottomSheet.native.js
- packages/blade-old/src/molecules/BottomSheet/__tests__/__snapshots__/BottomSheet.native.test.js.snap
- packages/blade-old/src/molecules/Modal/Modal.native.js
- packages/blade-old/src/tokens/theme.web.js
Add a new category `overlay`
[Slack Thread](https://razorpay.slack.com/archives/CTKFJ1QVC/p1622114007011100?thread_ts=1621419901.022400&cid=CTKFJ1QVC)
Fixes # (issue)
Fixes the inconsistencies in between light and dark theme.
Please delete options that are not relevant.
No changes to be tested for light theme. Modal and Backdrop can be checked for the dark theme
> chore(theme): add overlay colors

- .changeset/big-adults-burn.md
- packages/blade-old/src/molecules/BottomSheet/BottomSheet.native.js
- packages/blade-old/src/molecules/BottomSheet/BottomSheetFooter.native.js
- packages/blade-old/src/molecules/Modal/Modal.native.js
- packages/blade-old/src/molecules/Modal/ModalHeader.native.js
- packages/blade-old/src/tokens/theme.web.js
Fixes the BottomSheet and Modal Background Color for Dark Theme by adding a new variant under background section.
[Slack Thread](https://razorpay.slack.com/archives/CTKFJ1QVC/p1624011708001500?thread_ts=1621419901.022400&cid=CTKFJ1QVC)
BottomSheet, Modal in Darktheme
> style(theme): Change variant for BottomSheet and Modal background

- .changeset/famous-bulldogs-change.md
- .eslintignore
- .eslintrc.js
- .gitignore
- .prettierignore
- packages/blade/.babelrc.js
- packages/blade/package.json
- packages/blade/rollup.config.js
- packages/blade/scripts/generateRootImports.js
- packages/blade/src/components/index.ts
- packages/blade/src/tokens/global/index.ts
- packages/blade/src/tokens/index.ts
- packages/blade/src/tokens/theme/index.ts
- packages/blade/src/tokens/theme/overrideTheme.ts
- packages/blade/src/utils/useColorScheme/useColorScheme.ts
- packages/blade/tsconfig.json
- tsconfig.json
- yarn.lock
This PR implements the shipping strategy for Blade to npm registry. The details of the approach are mentioned in this [RFC](https://github.com/razorpay/blade/blob/blade/rfc-bundling/rfcs/2021-06-15-shipping-blade.md)
> feat(blade): add rollup to build blade

- .changeset/green-cars-build.md
- packages/blade/package.json
Fixes typo in `exports` field in `package.json`
> fix(blade): typo in exports field

- .changeset/clean-lies-watch.md
- packages/blade-old/src/atoms/TextArea/__tests__/__snapshots__/TextArea.native.test.js.snap
- packages/blade-old/src/atoms/TextInput/TextInput.native.js
- packages/blade-old/src/atoms/TextInput/TextInput.web.js
- packages/blade-old/src/atoms/TextInput/__tests__/__snapshots__/TextInput.native.test.js.snap
- packages/blade-old/src/atoms/TextInput/__tests__/__snapshots__/TextInput.web.test.js.snap
- packages/blade-old/src/icons/Eye/Eye.native.js
- packages/blade-old/src/icons/Eye/Eye.web.js
- packages/blade-old/src/icons/Eye/index.js
- packages/blade-old/src/icons/EyeOff/EyeOff.native.js
- packages/blade-old/src/icons/EyeOff/EyeOff.web.js
- packages/blade-old/src/icons/EyeOff/index.js
- packages/blade-old/src/icons/index.js
Enables use-case for adding password visibility toggler
> Allow textinput right icon to be touchable

- .changeset/purple-guests-explain.md
- packages/blade-old/src/icons/UserCheck/UserCheck.native.js
- packages/blade-old/src/icons/UserCheck/UserCheck.web.js
- packages/blade-old/src/icons/UserCheck/index.js
- packages/blade-old/src/icons/UserClose/UserClose.native.js
- packages/blade-old/src/icons/UserClose/UserClose.web.js
- packages/blade-old/src/icons/UserClose/index.js
- packages/blade-old/src/icons/index.js
This PR adds following icons 
- UserCheck
- UserClose
> feat(icons): Add icons

- .changeset/metal-chairs-sneeze.md
- packages/blade/src/tokens/global/typography.ts
There was a mistake in the typography scale of the desktop. This PR fixes that.
> fix(blade): update desktop typography scale

- .changeset/olive-apes-rhyme.md
- packages/blade/src/components/BladeProvider/emptyTheme.ts
- packages/blade/src/tokens/global/typography.ts
This PR adds `lineheight` tokens for mobile and desktop
> fix(blade): add lineheight tokens

- .github/workflows/semgrep.yml
Semgrep security update - adds delta scan on PRs and full scan on master
> chore(semgrep): add delta scan on PRs and full scan on master

- packages/blade/docs/guides/Installation.stories.mdx
Add installation guide for react-native-reanimate
**Changes:**
> docs: add installation guide for react-native-reanimated

- .changeset/breezy-icons-obey.md
- .changeset/smooth-pets-own.md
- packages/blade-old/src/molecules/Modal/Modal.native.js
> chore(modal): add testID to modal

- packages/blade/.storybook/react/main.js
- packages/blade/package.json
- yarn.lock
- Added https://storybook.js.org/addons/@storybook/addon-a11y
> feat(a11y-tools): add storybook accessibility addon

- packages/blade/src/components/SkipNav/SkipNav.stories.tsx
Fixes vanishing react-native storybooks
> chore(blade): fix skipnav storybook

- rfcs/accessibility-checklist.md
Blade Component Accessibility Checklist
> docs(blade): add blade component accessibility checklist

- packages/types/package.json
> refactor: cleanup packages/types

- .changeset/why-i-do-this.md
> chore: add changeset for Link

- packages/blade/src/components/Link/BaseLink/BaseLink.tsx
- packages/blade/src/components/Link/BaseLink/StyledBaseLink.d.ts
- packages/blade/src/components/Link/BaseLink/StyledBaseLink.web.tsx
- packages/blade/src/components/Link/BaseLink/__tests__/BaseLink.native.test.tsx
- packages/blade/src/components/Link/BaseLink/__tests__/BaseLink.web.test.tsx
- packages/blade/src/components/Link/BaseLink/__tests__/__snapshots__/BaseLink.web.test.tsx.snap
- packages/blade/src/components/Link/BaseLink/useInteraction.ts
- packages/blade/src/components/Link/Link/Link.stories.tsx
- packages/blade/src/components/Link/Link/Link.tsx
- packages/blade/src/components/Link/Link/__tests__/Link.native.test.tsx
- packages/blade/src/components/Link/Link/__tests__/Link.web.test.tsx
- packages/blade/src/components/Link/Link/__tests__/__snapshots__/Link.web.test.tsx.snap
Changes in this PR?
- Changed all relative imports to aliased imports
-  🚩 snapshot updates
> refactor(blade): use aliased imports in link

- .changeset/forty-parents-think.md
- packages/blade/src/components/Button/BaseButton/BaseButton.tsx
- packages/blade/src/components/Button/BaseButton/__tests__/BaseButton.native.test.tsx
- packages/blade/src/components/Button/BaseButton/__tests__/BaseButton.web.test.tsx
- packages/blade/src/components/Button/Button/Button.tsx
Add proper types for onClick of `Button` & `BaseButton`
> chore: add appropriate types for onClick of Button & BaseButton

- .changeset/clever-crews-smell.md
- packages/blade/src/components/Box/Box.d.ts
- packages/blade/src/components/Box/getBoxStyles.ts
- packages/blade/src/components/Checkbox/CheckboxGroup/CheckboxGroup.tsx
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.native.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.web.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/CheckboxGroup.native.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/CheckboxGroup.web.test.tsx.snap
- packages/blade/src/components/Form/FormLabel.tsx
- packages/blade/src/components/Form/Selector/SelectorLabel.native.tsx
- packages/blade/src/components/Form/Selector/SelectorLabel.web.tsx
New changes according to spacing spec: https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade---Payment-Light?node-id=15622%3A243373
- Fixed padding issues
- Fixed gutter between FormLabel
- Fixed alignment issues
> fix(blade): Checkbox design changes 

- CONTRIBUTING.md
So you do not have to spend yet another day setting up android 🥲
> docs(CONTRIBUTING): add android setup instructions

- .changeset/thirty-comics-enjoy.md
- packages/blade/src/components/Checkbox/Checkbox.tsx
- packages/blade/src/components/Checkbox/CheckboxGroup.stories.tsx
- packages/blade/src/components/Checkbox/CheckboxIcon/CheckboxIconWrapperStyles.ts
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.native.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.web.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/CheckboxGroup.native.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/CheckboxGroup.web.test.tsx.snap
- packages/blade/src/components/Form/Selector/SelectorGroupField.tsx
- packages/blade/src/components/Radio/Radio.stories.tsx
- packages/blade/src/components/Radio/Radio.tsx
- packages/blade/src/components/Radio/RadioGroup/RadioGroup.tsx
- packages/blade/src/components/Radio/RadioIcon/RadioIconWrapperStyles.ts
- packages/blade/src/components/Radio/__tests__/__snapshots__/Radio.native.test.tsx.snap
- packages/blade/src/components/Radio/__tests__/__snapshots__/Radio.web.test.tsx.snap
- packages/blade/src/components/Radio/__tests__/__snapshots__/RadioGroup.native.test.tsx.snap
- packages/blade/src/components/Radio/__tests__/__snapshots__/RadioGroup.web.test.tsx.snap
- Fixed alignment issues in Radio/Checkbox icon
- Fixed SelectorGroupField role
| Before   |      After      |  
|----------|:---------:|
| <img width="378" alt="Screenshot 2022-08-22 at 12 27 57 PM" src="https://user-images.githubusercontent.com/35374649/185858331-8210d5c6-e950-47c3-9c02-bff11e67b16e.png"> | <img width="378" alt="Screenshot 2022-08-22 at 12 28 41 PM" src="https://user-images.githubusercontent.com/35374649/185858480-9b9b81b4-f835-48fb-a089-6622ed84f325.png">
|
> fix(blade): radio & checkbox icon alignment

- .changeset/thirty-buttons-drive.md
- packages/blade/src/components/Icons/ArrowLeftIcon/ArrowLeftIcon.native.test.tsx
- packages/blade/src/components/Icons/ArrowLeftIcon/ArrowLeftIcon.tsx
- packages/blade/src/components/Icons/ArrowLeftIcon/ArrowLeftIcon.web.test.tsx
- packages/blade/src/components/Icons/ArrowLeftIcon/__snapshots__/ArrowLeftIcon.native.test.tsx.snap
- packages/blade/src/components/Icons/ArrowLeftIcon/__snapshots__/ArrowLeftIcon.web.test.tsx.snap
- packages/blade/src/components/Icons/ArrowLeftIcon/index.ts
- packages/blade/src/components/Icons/ArrowUpIcon/ArrowUpIcon.native.test.tsx
- packages/blade/src/components/Icons/ArrowUpIcon/ArrowUpIcon.tsx
- packages/blade/src/components/Icons/ArrowUpIcon/ArrowUpIcon.web.test.tsx
- packages/blade/src/components/Icons/ArrowUpIcon/__snapshots__/ArrowUpIcon.native.test.tsx.snap
- packages/blade/src/components/Icons/ArrowUpIcon/__snapshots__/ArrowUpIcon.web.test.tsx.snap
- packages/blade/src/components/Icons/ArrowUpIcon/index.ts
- packages/blade/src/components/Icons/iconMap.ts
- packages/blade/src/components/Icons/index.tsx
Adds 2 new icons
- ArrowUpIcon
- ArrowLeftIcon
> feat(icons): arrow up and arrow left 

- packages/blade/docs/guides/Intro.stories.mdx
Updates the current state section
- Removes image showing current state (hard to maintain)
> docs(INTRO): update current state section

- CONTRIBUTING.md
Some tips and troubleshooting guidelines to help people solve common development pains
> docs(CONTRIBUTING): add tips and troubleshooting guidelines

- .changeset/spicy-shrimps-begin.md
- packages/blade/src/components/Icons/RefreshLeftIcon/RefreshLeftIcon.native.test.tsx
- packages/blade/src/components/Icons/RefreshLeftIcon/RefreshLeftIcon.tsx
- packages/blade/src/components/Icons/RefreshLeftIcon/RefreshLeftIcon.web.test.tsx
- packages/blade/src/components/Icons/RefreshLeftIcon/__snapshots__/RefreshLeftIcon.native.test.tsx.snap
- packages/blade/src/components/Icons/RefreshLeftIcon/__snapshots__/RefreshLeftIcon.web.test.tsx.snap
- packages/blade/src/components/Icons/RefreshLeftIcon/index.ts
- packages/blade/src/components/Icons/iconMap.ts
- packages/blade/src/components/Icons/index.tsx
> feat(icons): refresh-left icon

- CODEOWNERS
- CONTRIBUTING.md
- Added some notes to CONTRIBUTING file to help simplify the process and reduce any confusions
- Minor tweaks in CONTRIBUTING
- Added my github username to CODEOWNERS 🕺🏻
> docs(CONTRIBUTING): update contributing according to latest xcode

- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/package.json
- packages/blade/src/components/Typography/Code/Code.stories.tsx
- packages/blade/src/components/Typography/Code/Code.tsx
This PR adds Web and Native implementation for `Code` component.
**PR Stack**
> feat(Code): Implementation Web & Native

- .changeset/unlucky-steaks-sing.md
- packages/blade/src/components/Icons/MinusIcon/MinusIcon.native.test.tsx
- packages/blade/src/components/Icons/MinusIcon/MinusIcon.tsx
- packages/blade/src/components/Icons/MinusIcon/MinusIcon.web.test.tsx
- packages/blade/src/components/Icons/MinusIcon/__snapshots__/MinusIcon.native.test.tsx.snap
- packages/blade/src/components/Icons/MinusIcon/__snapshots__/MinusIcon.web.test.tsx.snap
- packages/blade/src/components/Icons/MinusIcon/index.ts
- packages/blade/src/components/Icons/iconMap.ts
- packages/blade/src/components/Icons/index.tsx
> feat(Icons): add MinusIcon

- .changeset/fifty-ghosts-call.md
- packages/blade/src/components/Badge/Badge.tsx
- packages/blade/src/components/Badge/StyledBadge.web.tsx
- packages/blade/src/components/Badge/__tests__/__snapshots__/Badge.native.test.tsx.snap
- packages/blade/src/components/Badge/__tests__/__snapshots__/Badge.web.test.tsx.snap
- packages/blade/src/components/Badge/getStyledBadgeStyles.ts
- packages/blade/src/components/Badge/types.ts
Removes border from Badge component as per Design Feedback
> chore: remove border from Badge component

- .changeset/tall-lamps-hope.md
- packages/blade/src/tokens/theme/bankingTheme.ts
- packages/blade/src/tokens/theme/paymentTheme.ts
This PR was opened by the Token Upload GitHub action. It updates source token files based on the payload from Figma Plugin.
> feat(tokens): update tokens

- packages/blade/src/components/Button/Button/Button.stories.tsx
> fix(Button): show icons in button stories

- packages/blade/src/components/Link/Link/Link.stories.tsx
> fix: show icon in link stories

- packages/blade/src/components/Badge/Badge.stories.tsx
> fix(Badge): show icons in badge stories

- .changeset/purple-windows-call.md
- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/src/components/Counter/Counter.stories.tsx
- packages/blade/src/components/Counter/Counter.tsx
- packages/blade/src/components/Counter/__tests__/Counter.native.test.tsx
- packages/blade/src/components/Counter/__tests__/Counter.web.test.tsx
- packages/blade/src/components/Counter/__tests__/__snapshots__/Counter.native.test.tsx.snap
- packages/blade/src/components/Counter/__tests__/__snapshots__/Counter.web.test.tsx.snap
- packages/blade/src/components/Counter/index.tsx
- packages/blade/src/components/index.ts
Changes: 
- Added counter component
Screenshots: 
Web: 
Native:
> feat: added counter component

- .changeset/wise-trainers-arrive.md
- packages/blade/src/components/index.ts
Adds final export and changeset for `Indicator`
> feat(Indicator): add final export

- packages/blade/src/components/Indicator/Indicator.stories.tsx
Matches existing stories of other components.
> **Note**
>
> `Indicator` needs to be published before it starts showing in the sandbox
> refactor(Indicator): add figma embed and sandbox

- packages/blade/package.json
- yarn.lock
update react-native from 0.66.4 to 0.66.5
> build: fix android build

- packages/blade/src/_helpers/storybook/Sandbox/Sandbox.native.tsx
- packages/blade/src/_helpers/storybook/Sandbox/Sandbox.web.tsx
- packages/blade/src/_helpers/storybook/Sandbox/index.ts
- packages/blade/src/components/Alert/Alert.stories.tsx
- packages/blade/src/components/Badge/Badge.stories.tsx
- packages/blade/src/components/Button/Button/Button.stories.tsx
- packages/blade/src/components/Button/IconButton/IconButton.stories.tsx
- packages/blade/src/components/Checkbox/Checkbox.stories.tsx
- packages/blade/src/components/Checkbox/CheckboxGroup.stories.tsx
- packages/blade/src/components/Counter/Counter.stories.tsx
- packages/blade/src/components/Icons/Icons.stories.tsx
- packages/blade/src/components/Indicator/Indicator.stories.tsx
- packages/blade/src/components/Input/OTPInput/OTPInput.stories.tsx
- packages/blade/src/components/Input/PasswordInput/PasswordInput.stories.tsx
- packages/blade/src/components/Input/TextArea/TextArea.stories.tsx
- packages/blade/src/components/Input/TextInput/TextInput.stories.tsx
- packages/blade/src/components/Link/Link/Link.stories.tsx
- packages/blade/src/components/Radio/Radio.stories.tsx
- packages/blade/src/components/SkipNav/SkipNav.stories.tsx
- packages/blade/src/components/Spinner/Spinner/Spinner.stories.tsx
- packages/blade/src/components/Typography/Code/Code.stories.tsx
- packages/blade/src/components/Typography/Heading/Heading.stories.tsx
- packages/blade/src/components/Typography/Text/Text.stories.tsx
- packages/blade/src/components/Typography/Title/Title.stories.tsx
- packages/blade/src/components/VisuallyHidden/VisuallyHidden.stories.tsx
Fix for comment https://github.com/razorpay/blade/pull/844#discussion_r1023710801
Changes Sandbox exports to named exports
> refactor(Sandbox): change Sandbox exports

- packages/blade/src/components/Button/IconButton/IconButton.stories.tsx
Getting the error in current playground - https://master--61c19ee8d3d282003ac1d81c.chromatic.com/?path=/docs/components-iconbutton--icon-button
Fixed it in this PR
> fix(IconButton.stories.tsx): playground example error

- packages/blade/src/components/Checkbox/Checkbox.tsx
- packages/blade/src/components/Form/Selector/SelectorInput.native.tsx
- packages/blade/src/components/Form/Selector/SelectorInput.web.tsx
- packages/blade/src/components/Radio/Radio.tsx
changed the prop name in `SelectorInput` component as  mentioned [here ](https://github.com/razorpay/blade/blob/master/packages/blade/src/components/Radio/Radio.tsx#L95)
> chore: replaced `isNegative` prop with `hasError`

- .editorconfig
Fixes: https://github.com/razorpay/blade/issues/672
Added editor config:
> chore: added editor config

- packages/blade/src/components/ProgressBar/ProgressBar.stories.tsx
- packages/blade/src/components/ProgressBar/ProgressBar.tsx
- packages/blade/src/components/ProgressBar/__tests__/ProgressBar.native.test.tsx
- packages/blade/src/components/ProgressBar/__tests__/ProgressBar.web.test.tsx
- packages/blade/src/components/ProgressBar/__tests__/__snapshots__/ProgressBar.native.test.tsx.snap
- packages/blade/src/components/ProgressBar/__tests__/__snapshots__/ProgressBar.web.test.tsx.snap
- Add stories for `ProgressBar`
- Add tests for `ProgressBar`
> feat: add tests and stories for `ProgressBar`

- packages/blade/src/@types/globals.d.ts
- packages/blade/src/components/Input/BaseInput/__tests__/BaseInput.native.test.tsx
- packages/blade/src/components/Input/OTPInput/__tests__/OTPInput.native.test.tsx
- packages/blade/src/components/Input/PasswordInput/__tests__/PasswordInput.native.test.tsx
- packages/blade/src/components/Input/TextArea/__tests__/TextArea.native.test.tsx
- packages/blade/src/components/Input/TextInput/__tests__/TextInput.native.test.tsx
fixes https://github.com/razorpay/blade/issues/720
> fix: added jest-native typings

- packages/blade/src/components/Typography/Text/__tests__/Text.native.test.tsx
- packages/blade/src/components/Typography/Text/__tests__/Text.web.test.tsx
- packages/blade/tsconfig-generate-types.json
- packages/blade/tsconfig-generate-types.native.json
- packages/blade/tsconfig-generate-types.web.json
- packages/blade/tsconfig-typecheck.native.json
- packages/blade/tsconfig-typecheck.web.json
fixes https://github.com/razorpay/blade/issues/835
Removed exclusion of test files from tsconfig config.
> chore: typecheck test files on CI

- .changeset/wet-hotels-doubt.md
- packages/blade/package.json
> fix: npm install with react v18 & npm v7+

- .changeset/forty-rabbits-melt.md
- yarn.lock
ran https://www.npmjs.com/package/yarn-audit-fix since yarn doesn't support --fix
> chore: fix dependabot alerts

- packages/blade/src/_helpers/storybook/Sandbox/Sandbox.web.tsx
- packages/blade/src/components/Card/Card.stories.tsx
> chore: fix card sandbox

- packages/blade/src/components/Input/OTPInput/OTPInput.tsx
Missing commit from the #973 PR
> chore(OTPInput): cleanup `isMasked` logic and add comment

- packages/blade/src/_helpers/storybook/ComponentStatusTable.tsx
Updated release status for Dropdown and Select and added ActionList
> feat(Dropdown): add dropdown release status in component status page

- packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx
Missed to post in review. Added a note so we do not have to scratch our heads while reading the code in future
> docs(Dropdown): add note on Safari bug

- packages/examples/basic/package.json
- packages/examples/basic/yarn.lock
- Add bundle analyzer and `analyze` command
- Disabling ESLint for start and build runs. It is conflicting randomly with outer eslint. Anyway its not important in examples.
> feat: add bundle analyzer to example

- .changeset/fast-bugs-cover.md
- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/src/components/Dropdown/Dropdown.stories.tsx
- packages/blade/src/components/Dropdown/Dropdown.tsx
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.native.test.tsx.snap
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.ssr.test.tsx.snap
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.web.test.tsx.snap
- packages/blade/src/components/Input/SelectInput/SelectInput.tsx
Fixes 2 bugs
- [Inifinite render](https://razorpay.slack.com/archives/CMQ3RBHEU/p1676970701130639?thread_ts=1676869625.828389&cid=CMQ3RBHEU)
- [positioning in display flex container](https://razorpay.slack.com/archives/CMQ3RBHEU/p1676871892270009?thread_ts=1676869625.828389&cid=CMQ3RBHEU)
> fix(Dropdown): infinite render onChange, positioning in flex

- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/src/components/Box/BaseBox/storybookArgTypes.ts
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/Box.stories.tsx
- packages/blade/src/components/Box/Box.tsx
- packages/blade/src/components/Box/LayoutPrimitivesDocs.tsx
- packages/blade/src/components/Box/__tests__/Box.native.test.tsx
- packages/blade/src/components/Box/__tests__/Box.ssr.test.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
- packages/blade/src/components/Box/__tests__/__snapshots__/Box.ssr.test.tsx.snap
- Add `as` property
- Add tests
- Add documentation example
> feat(Box): add support for `as` prop

- packages/blade/src/components/Box/LayoutPrimitivesDocs.tsx
Added link to recipe and breakpoints story
> feat(LayoutPrimitivesDoc): add references to recipe

- .changeset/silly-terms-check.md
- packages/blade/src/components/Box/__tests__/Box.ssr.test.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
- packages/blade/src/components/Box/__tests__/__snapshots__/Box.ssr.test.tsx.snap
- packages/blade/src/utils/metaAttribute/metaConstants.ts
> chore(blade): update meta constant of Box

- packages/blade/src/_helpers/storybook/ComponentStatusTable.tsx
https://update-component-status--61c19ee8d3d282003ac1d81c.chromatic.com/?path=/docs/guides-component-status--page
> feat(Layout Primitives): update component status

- .changeset/mighty-terms-thank.md
- packages/examples/with-multiple-theme-providers/README.md
- PR fixes a typo in the README.md for blade integration with multiple theme provider
> docs: fix prop typo in README.md for theme with multiple providers

- .changeset/three-lobsters-teach.md
- packages/blade/src/components/index.ts
I thought I removed it already 🙈
> fix: remove internal box export

- .changeset/tricky-scissors-shave.md
- packages/blade/src/components/BottomSheet/BottomSheet.stories.tsx
- packages/blade/src/components/BottomSheet/BottomSheetBody.web.tsx
Because of the overflow=hidden the content wasn't scrollable. 
I missed it earlier because i tested the scrolling logic with ActionList which already had an internal overflow=auto set.
> fix(blade): fix BottomSheet content scrolling

- .changeset/soft-bees-pay.md
- packages/blade/src/components/BottomSheet/BottomSheet.stories.tsx
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/components/BottomSheet/BottomSheetContext.ts
- packages/blade/src/components/Dropdown/Dropdown.tsx
Changes: 
- Fixes isOpen state bug in BottomSheet
- Simplifies the glue code between dropdown & bottomsheet
Video walkthrough: https://www.loom.com/share/f24fcb51b245431fbf1a0aeb53cea287
> fix(blade): bottomsheet isOpen state, simplify isOpen logic & glue code

- packages/blade/src/_helpers/storybook/ComponentStatusTable.tsx
> docs(ComponentStatusTable): update DatePicker plans

- packages/blade/CHANGELOG.md
Add warning in changelog to problematic releases and recommend upgrading to >= 8.2.3 where this issue was resolved
> docs(CHANGELOG): add note on broken releases

- .changeset/pretty-clocks-thank.md
- packages/blade/src/components/BottomSheet/BottomSheet.stories.tsx
- packages/blade/src/components/BottomSheet/types.ts
- Added jsdoc comments for each prop
- Added storybook controls for BottomSheet & BottomSheetHeader
- Added proper argTypes for controls with restricted component selection
- Added documentation about snapPoint logic behaviour
> docs(blade): improve BottomSheet documentation

- .changeset/six-points-shake.md
- packages/blade/src/components/Dropdown/__tests__/Dropdown.native.test.tsx
- packages/blade/src/components/Dropdown/__tests__/Dropdown.web.test.tsx
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.web.test.tsx.snap
- packages/blade/src/components/Dropdown/docs/DropdownWithSelect.stories.tsx
- packages/blade/src/components/Dropdown/docs/stories.ts
- packages/blade/src/components/Input/SelectInput/SelectInput.tsx
resolves #1211 
Had a falsy value check. But we should allow empty string to be passed down so we can reset the value.
> fix(SelectInput): single select value clear

- .changeset/early-hounds-eat.md
- packages/blade/src/components/Link/BaseLink/BaseLink.tsx
- packages/blade/src/components/Link/Link/Link.stories.tsx
- packages/blade/src/components/Link/Link/Link.tsx
> feat(Link): add `xsmall` Link size

- .changeset/old-radios-pump.md
- packages/blade/src/components/Amount/Amount.tsx
- packages/blade/src/components/Amount/__tests__/__snapshots__/Amount.ssr.test.tsx.snap
- packages/blade/src/components/Amount/__tests__/__snapshots__/Amount.web.test.tsx.snap
Amount component should ideally be `inline-flex` and not `flex` to avoid such issues - https://razorpay.slack.com/archives/CMQ3RBHEU/p1685967801896139?thread_ts=1685526177.654729&cid=CMQ3RBHEU
> fix(Amount): Amount display property

- .changeset/tame-ravens-roll.md
- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/src/components/Typography/Heading/Heading.stories.tsx
- packages/blade/src/components/Typography/Heading/Heading.tsx
- packages/blade/src/components/Typography/Heading/__tests__/Heading.native.test.tsx
- packages/blade/src/components/Typography/Heading/__tests__/Heading.web.test.tsx
- packages/blade/src/components/Typography/Heading/__tests__/__snapshots__/Heading.native.test.tsx.snap
- packages/blade/src/components/Typography/Heading/__tests__/__snapshots__/Heading.web.test.tsx.snap
- packages/blade/src/components/Typography/Title/Title.stories.tsx
- packages/blade/src/components/Typography/Title/Title.tsx
- packages/blade/src/components/Typography/Title/__tests__/Title.native.test.tsx
- packages/blade/src/components/Typography/Title/__tests__/Title.web.test.tsx
- packages/blade/src/components/Typography/Title/__tests__/__snapshots__/Title.native.test.tsx.snap
- packages/blade/src/components/Typography/Title/__tests__/__snapshots__/Title.web.test.tsx.snap
> feat(blade): added support for React.ReactNode on Title & Heading component

- CODEOWNERS
> chore: add @snitin315 to CODEOWNERS

- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/src/components/Accordion/Accordion.tsx
- packages/blade/src/components/Accordion/AccordionButton.native.tsx
- packages/blade/src/components/Accordion/styles.native.ts
- packages/blade/src/components/Accordion/styles.web.ts
- packages/blade/src/components/Collapsible/Collapsible.stories.tsx
- packages/blade/src/components/Collapsible/Collapsible.tsx
- packages/blade/src/components/Collapsible/CollapsibleBodyContent.native.tsx
- packages/blade/src/components/Collapsible/CollapsibleBodyContent.web.tsx
- packages/blade/src/components/Collapsible/CollapsibleButton.tsx
- packages/blade/src/components/Collapsible/CollapsibleChevronIcon.native.tsx
- packages/blade/src/components/Collapsible/CollapsibleChevronIcon.web.tsx
- packages/blade/src/components/Collapsible/commonStyles.ts
- packages/blade/src/components/Collapsible/styles.native.ts
- packages/blade/src/components/Collapsible/styles.web.ts
- packages/blade/src/components/Collapsible/types.ts
- This PR completes the Collapsible native implementation (Accordion isn't complete yet)
- Includes some refactors which were common for web and native
- Screen recording on ios and android below
https://github.com/razorpay/blade/assets/6682655/5c42c68a-23c7-43cf-8226-17fa20654aa9
https://github.com/razorpay/blade/assets/6682655/964b7bf2-621d-4e62-b8f6-a9227718fe8f
> feat(Collapsible) - add native implementation

- .changeset/tender-fans-rule.md
- .github/workflows/blade-pr-title-check.yml
- packages/blade/src/components/Input/SelectInput/SelectInput.tsx
> fix: Dropdown opening when clicked on ChevronDownIcon in disabled state

- .changeset/eight-emus-arrive.md
- .changeset/tasty-fans-build.md
- packages/blade/src/components/Typography/Heading/Heading.tsx
- packages/blade/src/components/Typography/Text/Text.tsx
- packages/blade/src/components/Typography/Title/Title.tsx
Fixes: https://github.com/razorpay/blade/issues/1330
Co-authored-by: archie252000 <arc252000@gmail.com>
> feat: add textDecorationLine support for typography

- .changeset/tame-buses-compete.md
- packages/blade/src/components/Box/BaseBox/baseBoxStyles.ts
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/Box.tsx
> feat: add background-image, size, position, origin, repeat props

- packages/blade/src/components/Divider/Divider.stories.tsx
**Updated stories:**
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
> chore: update divider stories

- .changeset/wild-melons-change.md
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.ssr.test.tsx
- packages/blade/src/components/BottomSheet/__tests__/__snapshots__/BottomSheet.ssr.test.tsx.snap
- packages/blade/src/utils/useWindowSize.ts
fixes #1407
Initialised the useWindowSize width & height to 0 to start from instead of accessing window.innerWidth. 
0 will work fine because either way on hydration we call the `handleResize` function right away inside useEffect to update the value with the actual window width/height
> fix(blade): bottomsheet ssr fix

- packages/blade/.storybook/react/preview.js
- packages/blade/docs/utils/useTheme.stories.mdx
- packages/blade/src/tokens/theme/overrideTheme.stories.tsx
- packages/blade/src/utils/index.ts
> docs(utils): add documentation for `useTheme`

- packages/blade/docs/guides/FAQ.stories.mdx
- packages/blade/src/utils/isValidAllowedChildren/isValidAllowedChildren.ts
- Adds FAQ section 
- Adds #1367 as an FAQ
> feat: add FAQ section

- .changeset/fair-trainers-dance.md
- packages/blade/src/components/Collapsible/CollapsibleChevronIcon.native.tsx
- packages/blade/src/components/Collapsible/CollapsibleChevronIcon.web.tsx
- packages/blade/src/components/Collapsible/commonStyles.ts
> fix: collapsible arrow orientation when direction is top

- .changeset/brave-drinks-cry.md
- packages/razorsharp/package.json
- packages/razorsharp/src/code/blade/components/box/box.ts
- packages/razorsharp/src/code/blade/utils/color.ts
- packages/razorsharp/src/code/figmaUtils/convertIntoNodes.ts
- packages/razorsharp/src/code/types/Blade.ts
- yarn.lock
Closes https://github.com/razorpay/blade/issues/1400
1. Fix bug with `justifyContent` and `alignItems` generating incorrect values
2. Fix bug with incorrect value of color tokens getting generated
3. Improve algo that generates width, height, maxWidth, maxHeight, and flex grow properties
> fix: bugs in razorsharp

- packages/blade/src/components/Tag/_decisions/decisions.md
[**✨ Pretty Document ✨**](https://github.com/razorpay/blade/blob/tag/api-decision/packages/blade/src/components/Tag/_decisions/decisions.md)
> docs(Tag): Tags API Decision

- .changeset/tough-cherries-hope.md
- packages/blade/src/components/Box/BaseBox/baseBoxStyles.ts
> fix: add border-style when border width or color is set

- packages/blade-coverage-extension/background_script.js
- packages/blade-coverage-extension/src/App.tsx
- Fixed parent selector in coverage script plugin
- Added highlight node option 
https://github.com/razorpay/blade/assets/35374649/df4c0ede-c440-4be8-9ce2-f2e7149d8915
> fix: coverage script parent selector & add highlight nodes option

- .changeset/cyan-bottles-prove.md
- packages/blade/src/components/Modal/Modal.web.tsx
- packages/blade/src/components/Modal/__tests__/Modal.web.test.tsx
- packages/blade/src/components/Modal/docs/ModalDocs.tsx
> feat: add zIndex prop for Modal

- .changeset/chilly-fireants-sell.md
- packages/blade/src/components/Modal/Modal.web.tsx
- packages/blade/src/components/Modal/__tests__/Modal.web.test.tsx
- packages/blade/src/components/Tooltip/Tooltip.native.tsx
- packages/blade/src/components/Tooltip/Tooltip.web.tsx
- packages/blade/src/components/Tooltip/__tests__/Tooltip.native.test.tsx
- packages/blade/src/components/Tooltip/__tests__/Tooltip.web.test.tsx
- packages/blade/src/components/Tooltip/__tests__/__snapshots__/Tooltip.native.test.tsx.snap
- packages/blade/src/components/Tooltip/__tests__/__snapshots__/Tooltip.web.test.tsx.snap
- packages/blade/src/components/Tooltip/constants.ts
- packages/blade/src/components/Tooltip/types.ts
> feat: add zIndex prop to Tooltip

- packages/blade/src/components/Link/BaseLink/BaseLink.tsx
- packages/blade/src/components/Modal/Modal.native.tsx
- packages/blade/src/components/Modal/Modal.web.tsx
- packages/blade/src/components/Modal/types.ts
- packages/blade/src/components/Typography/BaseText/types.ts
- packages/blade/src/components/Typography/Code/Code.tsx
- packages/blade/src/components/Typography/Heading/Heading.tsx
- packages/blade/src/components/Typography/Text/Text.tsx
- packages/blade/src/components/Typography/Title/Title.tsx
> fix: abstract textsizes as BaseTextSizes

- .changeset/ninety-foxes-call.md
- packages/blade/src/components/Box/Box.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
Resolve https://github.com/razorpay/blade/issues/1480
> fix(Box): handle `undefined` for `backgroundColor` prop

- packages/blade/CHANGELOG.md
Updated in[ release notes](https://github.com/razorpay/blade/releases/tag/%40razorpay%2Fblade%409.5.0) too.
[Ref 1](https://razorpay.slack.com/archives/C01H13RTF8V/p1691390268370179?thread_ts=1691389406.209509&cid=C01H13RTF8V), [Ref 2](https://razorpay.slack.com/archives/CMQ3RBHEU/p1691573718179709?thread_ts=1689159775.991879&cid=CMQ3RBHEU)
> docs: add note in CHANGELOG for compatibility with jest

- .changeset/bright-zoos-drive.md
- packages/blade/src/components/Switch/Switch.tsx
- packages/blade/src/components/Switch/__tests__/__snapshots__/Switch.web.test.tsx.snap
Fixes https://github.com/razorpay/blade/issues/1506
> fix(Switch): correct cursor style in disabled state

- .changeset/ninety-bulldogs-walk.md
- packages/blade/src/components/Box/BaseBox/baseBoxStyles.ts
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/Box.stories.tsx
- packages/blade/src/components/Box/Box.tsx
- packages/blade/src/components/Box/styledProps/getStyledProps.ts
- packages/blade/src/components/Skeleton/Skeleton.tsx
Resolve https://github.com/razorpay/blade/issues/1449
Resolve https://github.com/razorpay/blade/issues/1381
We're excited to unveil the latest update for `Box`! Enjoy draggable elements, onDrag* & onDrop events, pointerEvents, and placeItems props. Elevate your UI with unparalleled control and flexibility. 
https://github.com/razorpay/blade/assets/46647141/e6ab16bf-c94f-4fb3-8ce1-9e1a921105a2
> feat(Box): add `draggable`,`onDrag*`,`onDrop`,`pointerEvents`,`placeItems`

- .changeset/lovely-icons-beg.md
- packages/blade/src/components/List/List.stories.tsx
- packages/blade/src/components/List/List.tsx
- packages/blade/src/components/List/__tests__/List.native.test.tsx
- packages/blade/src/components/List/__tests__/List.web.test.tsx
- packages/blade/src/components/List/__tests__/__snapshots__/List.native.test.tsx.snap
- packages/blade/src/components/List/__tests__/__snapshots__/List.web.test.tsx.snap
- packages/blade/src/components/List/listTokens.ts
Fixes: #1519 
Adds large size for List component
> feat: add large size to List component

- packages/blade/src/utils/storybook/ComponentStatusTable.tsx
This PR updates the `Chip` component status.
> docs(ComponentStatus): mark the `Chip` component as released

- .changeset/fresh-days-move.md
- packages/blade/src/components/Amount/Amount.tsx
- packages/blade/src/components/Amount/__tests__/Amount.native.test.tsx
- packages/blade/src/components/Amount/__tests__/Amount.web.test.tsx
Fixes https://github.com/razorpay/blade/issues/1572
> fix(Amount): correctly round the value upto 2 decimal places

- packages/blade/src/components/Chip/ChipGroup.stories.tsx
> docs(Chip): update codesandbox example

- packages/blade/src/utils/storybook/ComponentStatusTable.tsx
- Removed pagination since it will be taken together with Table. 
- Marked slot as ready and changed it's released version in to same as the Card one even though there is no code for this, can't figure out a better place to put this. 
- Marked table & tabs in design
> chore: update status table

- packages/blade/src/components/Card/Card.tsx
- packages/blade/src/components/Card/CardInteractive.stories.tsx
- packages/blade/src/components/Card/CardRoot.web.tsx
- packages/blade/src/components/Card/LinkOverlay.web.tsx
- packages/blade/src/components/Card/__tests__/__snapshots__/Card.ssr.test.tsx.snap
- packages/blade/src/components/Card/__tests__/__snapshots__/Card.web.test.tsx.snap
- packages/blade/src/components/Card/__tests__/__snapshots__/CardInteractive.web.test.tsx.snap
- packages/blade/src/components/Card/constants.ts
> fix(blade): fixed link overlay not working when wrapper is relative

- .changeset/new-balloons-smash.md
- packages/blade/src/components/Button/BaseButton/buttonTokens.ts
- packages/blade/src/components/Icons/Icons.stories.tsx
- packages/blade/src/components/Icons/index.tsx
- packages/blade/src/components/Icons/useIconProps/useIconProps.tsx
> feat(Icon): add default value for `size` & `color` props

- .changeset/green-lobsters-rule.md
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/Box.stories.tsx
- packages/blade/src/components/Box/Box.tsx
- packages/blade/src/components/Box/__tests__/Box.native.test.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
> chore(blade): added id to box

- .changeset/red-boats-give.md
- packages/blade/src/components/Box/BaseBox/baseBoxStyles.ts
- packages/blade/src/components/Box/__tests__/Box.native.test.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
- packages/blade/src/components/Box/__tests__/__snapshots__/Box.native.test.tsx.snap
- packages/blade/src/components/Box/__tests__/__snapshots__/Box.web.test.tsx.snap
Fix https://github.com/razorpay/blade/issues/1624
> fix(Box): correctly apply border styles

- packages/blade/src/components/Link/Link/Link.stories.tsx
> docs(Link): fix neutral link story

- .changeset/fair-jobs-poke.md
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Chip/Chip.tsx
- packages/blade/src/components/Icons/index.tsx
Fix https://github.com/razorpay/blade/issues/1657
Fix https://github.com/razorpay/blade/issues/1658
> feat: support `brand*` colors on Icon and borderColor

- .changeset/dirty-coins-heal.md
Add changeset for https://github.com/razorpay/blade/pull/1635
> docs: add changeset for #1635

- .changeset/wild-lies-kiss.md
- packages/blade/src/components/Carousel/Carousel.web.tsx
Fixes: https://razorpay.slack.com/archives/C01H13RTF8V/p1697115534165289
> fix: carousel indicator sync bug

- .changeset/popular-mangos-relate.md
- packages/blade/src/components/Input/BaseInput/BaseInput.tsx
Fixes https://github.com/razorpay/blade/issues/1682
> fix(Input): ensure correct value passing for trailingFooterSlot & trailingHeaderSlot

- .changeset/rich-baboons-dream.md
- packages/blade/src/components/Box/BaseBox/baseBoxStyles.ts
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/Box.stories.tsx
- packages/blade/src/components/Box/Box.tsx
Fixes https://github.com/razorpay/blade/issues/1394
Fixes https://github.com/razorpay/blade/issues/1679
> feat(Box): add `transform`, `transformOrigin`, `clipPath`, `opacity`, & `visibility` props

- packages/blade-coverage-extension/background_script.js
Pulls in changes from https://github.com/razorpay/frontend-core-tools/pull/96
> feat(blade-coverage-script): filter out svgs and media elements

- .changeset/moody-ads-bow.md
- packages/blade/src/components/Alert/Alert.tsx
- packages/blade/src/components/Alert/__tests__/Alert.native.test.tsx
- packages/blade/src/components/Alert/__tests__/Alert.web.test.tsx
- packages/blade/src/components/Alert/__tests__/__snapshots__/Alert.native.test.tsx.snap
- packages/blade/src/components/Alert/__tests__/__snapshots__/Alert.web.test.tsx.snap
- packages/blade/src/components/Alert/styles.ts
- packages/blade/src/components/Alert/types.ts
Fixes https://github.com/razorpay/blade/issues/1727
> fix(Alert): correct color prop behavior

- packages/blade/src/utils/storybook/Sandbox/Sandbox.web.tsx
> fix(docs): font in sandpack

- .changeset/breezy-turtles-love.md
- packages/blade/src/components/Input/DropdownInputTriggers/AutoComplete.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/AutoComplete.web.test.tsx
Fix https://github.com/razorpay/blade/issues/1676
> fix(Autocomplete): enhance input handling for controlled scenarios

- .changeset/silver-keys-press.md
- packages/blade/src/components/Dropdown/__tests__/Dropdown.web.test.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/BaseDropdownInputTrigger.tsx
Fix https://github.com/razorpay/blade/issues/1721
> fix(Dropdown): enhance tag selection handling

- .github/workflows/ai-pr-review.yml
Adds https://github.com/coderabbitai/ai-pr-reviewer
This would suggest us some meaningful changes to our PRs. Lets try this for a while at least.
> feat: add AI PR Reviewer

- .changeset/witty-mails-tickle.md
- packages/blade/src/components/Popover/Popover.stories.tsx
- packages/blade/src/components/Popover/PopoverContent.tsx
- packages/blade/src/components/Popover/__tests__/__snapshots__/Popover.native.test.tsx.snap
- packages/blade/src/components/Popover/__tests__/__snapshots__/Popover.web.test.tsx.snap
Fixes https://razorpay.slack.com/archives/CMQ3RBHEU/p1698396907879829
Resolves #1757
> chore: fix popover close button background

- packages/blade/.storybook/react/manager-head.html
- packages/blade/docs/guides/Intro.stories.mdx
- packages/blade/src/utils/storybook/StoryPageWrapper.tsx
Fixes
- [white text of title in dark mode](https://razorpay.slack.com/archives/G01B3LQ9H0W/p1698398619131009)
- [border-color for top panel](https://razorpay.slack.com/archives/G01B3LQ9H0W/p1698392792331999)
> docs: fix border color and dark theme titles

- packages/blade/src/components/ActionList/ActionList.stories.tsx
- packages/blade/src/components/ActionList/_KitchenSink.ActionList.stories.tsx
- packages/blade/src/components/ActionList/docs/ActionList.stories.mdx
closes #1611 
Changes Made: 
- Added 2 files, `ActionList.stories.tsx` containing story combinations for ActionList and `_KitcheSink.ActionList.stories.tsx` for it's Kitchensink dump.
Required TODO: @saurabhdaware can you give me some idea here about `argTypes` and `args`?  not sure how to show this on story docs.
> feat(ActionList): added stories and kitchensink for combinations

- .changeset/honest-glasses-sin.md
- packages/blade/src/components/BottomSheet/BottomSheetBackdrop.native.tsx
- packages/blade/src/components/BottomSheet/BottomSheetBackdrop.web.tsx
- packages/blade/src/components/Modal/ModalBackdrop.tsx
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.native.test.tsx.snap
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.web.test.tsx.snap
- packages/blade/src/tokens/theme/theme.ts
migrates the overlay tokens as per new change in #1768
> feat: migrate overlay tokens

- packages/blade/src/storybook-recipes/SimpleDashboard.stories.tsx
- packages/blade/src/storybook-recipes/SimpleForm.stories.tsx
Recipes were failing because of incorrect import
> fix(Recipes): Imports of recipes in storybook

- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.native.test.tsx
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.ssr.test.tsx
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.web.test.tsx
> fix(Dropdown): flaky tests test

- .changeset/olive-taxis-fix.md
- packages/blade/src/components/Input/BaseInput/StyledBaseInput.native.tsx
- packages/blade/src/components/Input/BaseInput/StyledBaseInput.web.tsx
- packages/blade/src/components/Input/TextInput/TextInput.tsx
- packages/blade/src/components/Input/TextInput/__tests__/TextInput.native.test.tsx
- packages/blade/src/components/Input/TextInput/__tests__/TextInput.web.test.tsx
Resolves #1560.
I have passed onClick prop of BaseInput to TextInput.
Hope this is the right way.
Wrote a test too.
Please let me know of any changes, thanks.
> feat(TextInput): add onClick prop

- packages/blade/.storybook/react/main.js
- packages/blade/src/components/Amount/Amount.tsx
- packages/blade/src/components/Card/Card.stories.tsx
- packages/blade/src/components/Card/Card.tsx
- packages/blade/src/components/Card/CardFooter.tsx
- packages/blade/src/components/Card/CardHeader.tsx
- packages/blade/src/components/Card/CardRoot.native.tsx
- packages/blade/src/components/Card/CardRoot.web.tsx
- packages/blade/src/components/Card/CardSurface.native.tsx
- packages/blade/src/components/Card/CardSurface.web.tsx
- packages/blade/src/components/Card/types.ts
- packages/blade/src/components/Divider/Divider.tsx
- packages/blade/src/components/Indicator/Indicator.stories.tsx
- packages/blade/src/components/Indicator/Indicator.tsx
- packages/blade/src/components/Typography/Code/Code.tsx
- packages/blade/src/components/index.ts
- packages/blade/src/tokens/global/border.ts
- packages/blade/src/tokens/theme/overrideTheme.ts
- packages/blade/src/tokens/theme/theme.ts
- packages/blade/src/utils/storybook/StoryPageWrapper.tsx
- packages/blade/tsconfig.json
- Fix tokens and colors
- Add new padding and and margin props to header and footer
- Remove `surfaceLevel` and add `backgroundColor`
- add `borderRadius`
> feat(Card): migrate Card to new designs

- packages/blade/src/components/Card/Card.stories.tsx
- packages/blade/src/components/Card/CardInteractive.stories.tsx
- packages/blade/src/components/SpotlightPopoverTour/docs/Tour.stories.tsx
- packages/blade/src/components/Tabs/Tabs.stories.tsx
Resolves issues with stories being rendered incorrectly because of changes in storybook's argTypes's defaultValue
> chore: fix stories using defaultValue in argTypes

- packages/blade/docs/guides/Intro.stories.mdx
> chore: add rebranding info to intro page

- packages/blade/src/utils/storybook/ComponentStatusTable.tsx
- packages/blade/src/utils/storybook/componentStatusData.ts
> chore: add Rebranded In Column to component status table

- packages/blade/docs/tokens/ThemeExplorer.stories.mdx
- packages/blade/package.json
- yarn.lock
> feat: add theme explorer

- .changeset/violet-donuts-carry.md
- packages/blade/src/components/Skeleton/Skeleton.tsx
Resolves #1946 
In this short PR I've changed - packages/blade/src/components/Skeleton/Skeleton.tsx file.
Lines added are -      
minWidth={minWidth}
minHeight={minHeight}
These changes have not caused any errors while building the services and no dependency issues were found. 
If there is any issue that arises please let me know. I'll try to fix it asap !
Thank You.
> feat(Skeleton): add minHeight and minWidth prop 

- .changeset/gentle-boxes-divide.md
- packages/blade/src/components/Card/Card.tsx
- packages/blade/src/components/Card/CardRoot.native.tsx
- packages/blade/src/components/Card/types.ts
> fix(blade): expose card event type

- .vscode/settings.json
- README.md
Installation link updated.
Fixes #1974
> fix: broken installation link fixed

- .changeset/angry-turtles-mate.md
- packages/blade/src/components/Toast/Toast.stories.tsx
- packages/blade/src/components/Toast/Toast.web.tsx
- packages/blade/src/components/Toast/ToastContainer.web.tsx
- packages/blade/src/utils/metaAttribute/metaConstants.ts
- packages/blade/src/utils/storybook/ComponentStatusTable.tsx
- packages/blade/src/utils/storybook/componentStatusData.ts
> chore: update component status page

- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.ssr.test.tsx.snap
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.web.test.tsx.snap
- packages/blade/src/components/Input/BaseInput/BaseInputTagSlot.web.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/__snapshots__/AutoComplete.ssr.test.tsx.snap
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/__snapshots__/AutoComplete.web.test.tsx.snap
- packages/blade/src/components/Tag/AnimatedTag.web.tsx
- packages/blade/src/components/Tag/Tag.tsx
- packages/blade/src/components/Tag/__tests__/__snapshots__/Tag.native.test.tsx.snap
- packages/blade/src/components/Tag/__tests__/__snapshots__/Tag.ssr.test.tsx.snap
- packages/blade/src/components/Tag/__tests__/__snapshots__/Tag.web.test.tsx.snap
Backtracking issue fixes from #2017 and #2021
> fix(Dropdown): scrollbar visibility and truncation for v10

- packages/blade/docs/guides/Intro.stories.mdx
> docs: add github link to main repo

- .github/workflows/blade-bundle-size.yml
> ci: update blade-bundle-size.yml

- packages/blade/src/components/Breadcrumb/Breadcrumb.stories.tsx
- packages/blade/src/utils/storybook/componentStatusData.ts
> chore: update component statuses

- .changeset/eighty-wombats-marry.md
- packages/blade/src/components/index.ts
> fix: add FileUpload exports

- .changeset/smart-poems-rest.md
- packages/blade/package.json
- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
- packages/examples/basic/package.json
- yarn.lock
This PR upgrades i18nify-js version and resolves https://github.com/razorpay/blade/issues/2036
> fix: i18nify-js dependency updated

- packages/blade/src/utils/storybook/componentStatusData.ts
Updates component status, to be merged after releasing the component.
> docs: mark FileUpload as released

- packages/blade/src/components/FileUpload/FileUpload.web.tsx
- Remove console.log
We should enable the `no-console` ESLint rule.
> chore: remove redundant console statement

- .changeset/silly-mayflies-approve.md
- packages/blade/src/components/Dropdown/dropdownUtils.ts
- packages/blade/src/components/Dropdown/useDropdown.ts
> fix(DropdownButton): dropdown focus item scrolling 

- packages/blade/src/utils/storybook/componentStatusData.ts
Updates component status page.
> docs: mark ButtonGroup as released

- .changeset/random-word-here.md
> chore: add changeset for table checkbox fix

- packages/blade/src/utils/storybook/componentStatusData.ts
> chore: update component status table

- .changeset/six-planes-wash.md
- packages/blade/codemods/migrate-progressbar/transformers/__test__/migrate-progressbar.test.ts
- packages/blade/codemods/migrate-progressbar/transformers/index.ts
> feat: add ProgressBar codemod

- .changeset/breezy-penguins-attend.md
- packages/blade/src/components/Chip/Chip.tsx
- packages/blade/src/components/Chip/ChipGroup.stories.tsx
- packages/blade/src/components/Chip/ChipGroup.tsx
- packages/blade/src/components/Chip/__tests__/ChipGroup.native.test.tsx
- packages/blade/src/components/Chip/__tests__/ChipGroup.web.test.tsx
- packages/blade/src/components/Chip/__tests__/__snapshots__/Chip.ssr.test.tsx.snap
- packages/blade/src/components/Chip/__tests__/__snapshots__/Chip.web.test.tsx.snap
- packages/blade/src/components/Chip/__tests__/__snapshots__/ChipGroup.native.test.tsx.snap
- packages/blade/src/components/Chip/__tests__/__snapshots__/ChipGroup.ssr.test.tsx.snap
- packages/blade/src/components/Chip/__tests__/__snapshots__/ChipGroup.web.test.tsx.snap
- packages/blade/src/components/Chip/chipTokens.ts
- packages/blade/src/components/Chip/types.ts
- packages/blade/src/components/Chip/useChipGroup.ts
[Support Ticket](https://razorpay.atlassian.net/jira/software/c/projects/FC/issues/FC-2856?jql=project%20%3D%20%22FC%22%20AND%20assignee%20%3D%20currentUser%28%29%20ORDER%20BY%20assignee%20DESC%2C%20created%20DESC)
> feat: add label & validation related props to ChipGroup

- .changeset/soft-tables-provide.md
- packages/blade/src/components/Modal/Modal.web.tsx
- packages/blade/src/components/Modal/ModalBody.web.tsx
- packages/blade/src/components/Modal/ModalFooter.web.tsx
- packages/blade/src/components/Modal/ModalHeader.web.tsx
- packages/blade/src/components/Modal/__tests__/Modal.web.test.tsx
- packages/blade/src/components/Modal/constants.ts
- packages/blade/src/utils/useVerifyAllowedChildren/useVerifyAllowedChildren.ts
fixes https://github.com/razorpay/blade/issues/2170
> fix: modal component failing to verify null component

- packages/blade/src/components/Dropdown/DropdownHeaderFooter.tsx
- packages/blade/src/components/Dropdown/__tests__/Dropdown.test.stories.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/AutoComplete.test.stories.tsx
Tests started failing after #2160. Fixed them here
> fix: Dropdown interaction tests

- .changeset/ninety-cycles-sit.md
- packages/blade/src/components/Input/PhoneNumberInput/PhoneNumberInput.web.tsx
- packages/blade/src/components/Input/PhoneNumberInput/types.ts
> chore: add placeholder prop in phone input

- packages/blade/scripts/generateBundleDiff.js
Show newly added component data in PR.
> chore: display added component data

- packages/blade-coverage-extension/package.json
- packages/blade-coverage-extension/src/App.tsx
- packages/blade-coverage-extension/yarn.lock
> fix: build issues with blade coverage extension

- .changeset/red-adults-dress.md
- packages/blade/src/components/Card/CardSurface.native.tsx
- packages/blade/src/components/Card/CardSurface.web.tsx
- packages/blade/src/components/Card/__tests__/__snapshots__/Card.web.test.tsx.snap
- packages/blade/src/components/Switch/__tests__/__snapshots__/Switch.native.test.tsx.snap
- packages/blade/src/components/Switch/__tests__/__snapshots__/Switch.ssr.test.tsx.snap
- packages/blade/src/components/Switch/__tests__/__snapshots__/Switch.web.test.tsx.snap
- packages/blade/src/components/Switch/switchTokens.ts
- Fixes Card Border Width
It had invalid value so it was picking browser default https://razorpay.slack.com/archives/C074E2N774G/p1716527521045049
- Fixes Switch colors
Colors in our switch component in code were different from colors on figma
> fix(Card, Switch): card border width, switch colors

- .changeset/hungry-toes-cheat.md
- packages/blade/package.json
- packages/blade/src/components/DatePicker/DateInput.web.tsx
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
- packages/blade/src/components/DatePicker/types.ts
- packages/blade/src/components/Input/BaseInput/BaseInput.tsx
- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
> fix: datepicker label alignment

- packages/blade/public/robots.txt
> feat: add robots.txt

- packages/blade/src/components/DatePicker/DateInput.web.tsx
- packages/blade/src/components/DatePicker/DatePicker.stories.tsx
> fix: width of datepicker inputs

- .changeset/dirty-poems-hang.md
> chore: add datepicker changeset

- .changeset/smart-mayflies-tell.md
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
> fix: datepicker zIndex issue and expose zIndex prop

- .changeset/slimy-taxis-retire.md
- packages/blade/src/components/DatePicker/DateInput.web.tsx
Reported on slack
https://github.com/razorpay/blade/assets/46647141/f25997d9-460b-4c3f-84a0-83820d914d8e
https://github.com/razorpay/blade/assets/46647141/1e7225bd-b16e-44b6-89c1-7576363e08df
> fix(DatePicker): correct input alignment without label

- .changeset/witty-swans-impress.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
- packages/blade/src/components/FileUpload/__tests__/__snapshots__/FileUpload.ssr.test.tsx.snap
- packages/blade/src/components/FileUpload/__tests__/__snapshots__/FileUpload.web.test.tsx.snap
Fix extra margin, reported on slack.
> fix(FileUpload): remove excessive margins

- .changeset/few-goats-cry.md
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
Fixes: https://github.com/razorpay/blade/issues/2248
> fix: bottomsheet initial focus triggering everytime

- .github/workflows/blade-bundle-size.yml
- packages/blade/scripts/generateBundleDiff.js
Fix workflow on master.
Its failing on master because of security rules, use a non master branch instead.
> ci: push bundle stats to non-master branch

- packages/blade/src/components/Drawer/__tests__/Drawer.test.stories.tsx
> ci: fix flaky drawer tests

- packages/blade/src/utils/storybook/componentStatusData.ts
> chore: update component status

- .changeset/lucky-plums-lie.md
- packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx
- packages/blade/src/components/Dropdown/docs/DropdownWithSelect.stories.tsx
- packages/blade/src/components/Dropdown/types.ts
- packages/blade/src/components/Menu/MenuOverlay.web.tsx
- packages/blade/src/components/Menu/types.ts
> feat(Menu, Dropdown): add width props on MenuOverlay and allow it in SelectInput Dropdown

- .changeset/famous-coats-watch.md
- packages/blade/src/components/ProgressBar/ProgressBar.tsx
- packages/blade/src/components/ProgressBar/__tests__/ProgressBar.web.test.tsx
- packages/blade/src/components/ProgressBar/__tests__/__snapshots__/ProgressBar.web.test.tsx.snap
Fix https://github.com/razorpay/blade/issues/2227
> fix(ProgressBar): show percentage with decimal when using as meter

- .changeset/dirty-singers-sparkle.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
[reported on slack](https://razorpay.slack.com/archives/C01H13RTF8V/p1719460671551749?thread_ts=1719209184.597759&cid=C01H13RTF8V)
don't use prop in useState 😭
> fix(FileUpload): correctly update errortText

- packages/blade/.storybook/react/global.css
- packages/blade/docs/guides/Installation.stories.mdx
> docs: improve installation documentation

- .changeset/curly-roses-peel.md
- packages/blade/src/components/Table/TablePagination.web.tsx
- packages/blade/src/components/Table/tokens.ts
- packages/blade/src/components/Table/types.ts
> fix: table footer background color

- .changeset/loud-brooms-hug.md
- packages/blade/src/components/DatePicker/DateInput.web.tsx
> fix: datepicker necessityIndicator

- packages/blade/src/components/Input/TextInput/TextInput.stories.tsx
- packages/blade/src/utils/storybook/componentStatusData.ts
The earlier usage was deprecated
> fix(TextInput.stories): add note for type number

- .changeset/spicy-buses-deny.md
- packages/blade/src/components/StepGroup/StepGroup.stories.tsx
- packages/blade/src/components/StepGroup/StepItem.web.tsx
- packages/blade/src/components/StepGroup/types.ts
Disabled state was missed in StepItem component. Added it.
> feat(StepItem): add disabled state for stepitem

- .changeset/lucky-ladybugs-lay.md
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.native.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.ssr.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.web.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/CheckboxGroup.ssr.test.tsx.snap
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/CheckboxGroup.web.test.tsx.snap
- packages/blade/src/components/FileUpload/__tests__/__snapshots__/FileUpload.ssr.test.tsx.snap
- packages/blade/src/components/FileUpload/__tests__/__snapshots__/FileUpload.web.test.tsx.snap
- packages/blade/src/components/Form/FormHint.tsx
- packages/blade/src/components/Form/FormHintWrapper.web.tsx
- packages/blade/src/components/Input/BaseInput/__tests__/__snapshots__/BaseInput.native.test.tsx.snap
- packages/blade/src/components/Input/BaseInput/__tests__/__snapshots__/BaseInput.ssr.test.tsx.snap
- packages/blade/src/components/Input/BaseInput/__tests__/__snapshots__/BaseInput.web.test.tsx.snap
- packages/blade/src/components/Input/PasswordInput/__tests__/__snapshots__/PasswordInput.ssr.test.tsx.snap
- packages/blade/src/components/Input/SearchInput/__tests__/__snapshots__/SearchInput.ssr.test.tsx.snap
- packages/blade/src/components/Input/SearchInput/__tests__/__snapshots__/SearchInput.web.test.tsx.snap
- packages/blade/src/components/Radio/__tests__/__snapshots__/Radio.ssr.test.tsx.snap
- packages/blade/src/components/Radio/__tests__/__snapshots__/RadioGroup.ssr.test.tsx.snap
- packages/blade/src/components/Radio/__tests__/__snapshots__/RadioGroup.web.test.tsx.snap
Fixes: https://razorpay.atlassian.net/browse/DSSUP-69
> fix: hint-text wrapping and alignment

- .changeset/poor-pumas-relate.md
- packages/blade/src/components/Tooltip/TooltipInteractiveWrapper.web.tsx
> fix: support overriding tooltip interactive wrapper display prop

- .changeset/old-cheetahs-protect.md
- packages/blade/src/components/DatePicker/CalendarFooter.web.tsx
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
- packages/blade/src/components/DatePicker/types.ts
Fixes: 
https://razorpay.atlassian.net/browse/DSSUP-72
https://razorpay.atlassian.net/browse/DSSUP-71
> feat: fix datepicker range selection bug & add onApply handler

- .changeset/negative-amount.md
> feat(Amount): add changeset for amount

- .changeset/clever-pigs-grow.md
- packages/blade/src/components/Table/Table.web.tsx
- packages/blade/src/components/Table/TableBody.web.tsx
- packages/blade/src/components/Table/__tests__/__snapshots__/Table.web.test.tsx.snap
- packages/blade/src/components/Table/types.ts
> feat(Table): test id for table row and loading state

- .changeset/tricky-clocks-smoke.md
- packages/blade/src/components/BottomSheet/BottomSheetStack.tsx
Fixes https://razorpay.atlassian.net/browse/DSSUP-165
> fix(blade): bottomsheet body scroll lock not clearing

- packages/blade/src/tokens/global/colors.ts
- packages/blade/src/tokens/theme/bladeTheme.ts
> Revert "feat(tokens): add new tokens"

- .changeset/poor-falcons-yawn.md
chore: add changeset for native event
> chore: add changeset for Trigger native event [FC-1234]

- CODEOWNERS
> chore: update code owner

- packages/blade/src/components/TopNav/docs/code.ts
- packages/blade/src/storybook-recipes/TopNavDashboard.stories.tsx
> chore: fix top nav sandboxes

- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
On master too it finds sha, we can just explicitly check for master sha
> fix(Stackblitz): fix for incorrect isPR condition for master

- .changeset/fair-beers-confess.md
- packages/blade/src/utils/useCallbackRef.ts
> fix(blade): fallback for useInsertionEffect

- .changeset/itchy-boxes-learn.md
- packages/blade/src/components/Card/CardInteractive.stories.tsx
- packages/blade/src/components/Card/CardRoot.web.tsx
- packages/blade/src/components/Card/__tests__/__snapshots__/Card.ssr.test.tsx.snap
- packages/blade/src/components/Card/__tests__/__snapshots__/Card.web.test.tsx.snap
- packages/blade/src/components/Card/__tests__/__snapshots__/CardInteractive.web.test.tsx.snap
this fixes - fix: unable to use switch inside card body
> fix: unable to use switch inside card body

- .changeset/neat-insects-rule.md
- packages/blade/src/components/index.ts
> feat(Elevate): add missing reexport for Elevate

- .changeset/sour-cherries-fry.md
- packages/blade/src/utils/types.ts
fix(blade): fix: data analytics attribute from another external module
> fix: data analytics no exported for v11

- packages/widget-figma-dev-handoff-checklist/package-lock.json
- packages/widget-figma-dev-handoff-checklist/snowflake-handoff-checklist/code.tsx
Added a new checklist item to the **Snowflake Handoff Checklist Widget** for Figma. The new checklist item will help designers add their issue ticket links directly to the widget.
A new addition for the item "Ticket Link"
> feat: new checklist item to snowflake handoff checklist figma widget

- .changeset/famous-eggs-turn.md
- packages/blade/src/components/Modal/Modal.web.tsx
- packages/blade/src/components/Modal/__tests__/__snapshots__/Modal.web.test.tsx.snap
- yarn.lock
Smaller reproduction of module federation issue: https://stackblitz.com/edit/nzgpqgh9?file=App.tsx
In module federated apps, styled-props are taking higher priority over styled-component's immediate style
> fix(Modal): remove position absolute from ModalContent

- .changeset/chatty-months-carry.md
- .github/workflows/blade-validate.yml
- .github/workflows/release.yml
- .gitignore
- package.json
- packages/blade/package.json
- packages/blade/scripts/generateDocsLockFile.mjs
- packages/blade/src/components/Card/Card.stories.tsx
- packages/blade/src/components/ChatMessage/docs/ChatMessage.stories.tsx
- packages/blade/src/components/DatePicker/DatePicker.stories.tsx
- packages/blade/src/components/Dropdown/docs/stories.ts
- packages/blade/src/utils/storybook/Sandbox/StackblitzEditor/Sandbox.web.tsx
- packages/blade/src/utils/storybook/Sandbox/StackblitzEditor/useEarlyFetch.ts
- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
- packages/blade/src/utils/storybook/Sandbox/dependencies.json
- yarn.lock
- **Before**: ~1min
- **After**: ~30sec
https://github.com/user-attachments/assets/5646ff49-2eb8-49f0-aa86-b8d8458d6304
> feat(storybook): pre-generate lock file for examples

- packages/blade/src/components/DetailedView/_decisions/decisions.md
> feat(DetailedView): add API decision

- .changeset/mighty-parents-tan.md
- packages/blade/src/components/Dropdown/FilterChipSelectInput.web.tsx
- packages/blade/src/components/Dropdown/docs/DropdownWithFilterChip.stories.tsx
- packages/blade/src/components/ListView/ListViewFilters.web.tsx
- packages/blade/src/components/ListView/docs/ListView.stories.tsx
> fix: list view improvements

- .changeset/wild-apricots-exist.md
- packages/blade/.storybook/react/preview-head.html
- packages/blade/src/components/BaseHeaderFooter/BaseHeader.tsx
- packages/blade/src/components/BaseHeaderFooter/BaseHeaderFooter.internal.stories.tsx
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.native.test.tsx
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.web.test.tsx
- packages/blade/src/components/Button/IconButton/IconButton.tsx
- packages/blade/src/components/Drawer/Drawer.web.tsx
- packages/blade/src/components/Drawer/DrawerSubcomponents.web.tsx
- packages/blade/src/components/Drawer/__tests__/__snapshots__/Drawer.web.test.tsx.snap
- packages/blade/src/components/Drawer/docs/Drawer.stories.tsx
- packages/blade/src/components/Drawer/types.ts
- packages/blade/src/components/Typography/Heading/Heading.tsx
Visual Changes in Drawer
- Change border-radius 
- Add spacing around the drawer
- Add backgroundImage property to DrawerHeader
> feat(Drawer): visual changes in drawer to add border radius

- .changeset/brave-needles-kneel.md
- packages/blade/src/components/ListView/ListViewFilters.web.tsx
ref - https://razorpay.slack.com/archives/CMQ3RBHEU/p1745595570629089?thread_ts=1744899419.740249&cid=CMQ3RBHEU
> fix: add accessibilityLabel in List View show more filter button

- .changeset/old-dancers-punch.md
- packages/blade/src/components/Input/PhoneNumberInput/CountrySelector.web.tsx
Adds virtualization to country selector in phone number input
> feat(PhoneNumberInput): add virtualization to phone number input

- .changeset/clean-news-talk.md
- packages/blade-mcp/src/server.ts
> fix: trying the mcp release

- .changeset/quick-moose-refuse.md
- package.json
- packages/blade-mcp/src/server.ts
- yarn.lock
> fix: publish mcp to npm

- .github/workflows/blade-interaction-tests.yml
ref - https://razorpay.slack.com/archives/C074E2N774G/p1746514802580139
> revert: Blade interaction tests to run on every commit 

- .changeset/weak-kangaroos-sip.md
- packages/blade-mcp/package.json
- packages/blade-mcp/src/server.ts
- yarn.lock
This PR fixes the compatibility of zod and mcp sdk versions
> fix: mcp zod version compatibility

- .changeset/weak-trainers-search.md
- packages/blade/src/components/TopNav/TabNav/TabNav.web.tsx
> fix(FC-3152): add data-analytics-* for TabNav

- .changeset/sharp-shoes-jog.md
- packages/blade-mcp/package.json
hopefully fixes https://razorpay.slack.com/archives/C01H13RTF8V/p1746701267711639?thread_ts=1746590694.426449&cid=C01H13RTF8V
> feat: add zod resolution

- .changeset/gorgeous-buses-attend.md
- packages/blade-mcp/README.md
- packages/blade-mcp/base-blade-template/.npmrc
- packages/blade-mcp/base-blade-template/package-lock.json
- packages/blade-mcp/base-blade-template/package.json
- packages/blade-mcp/src/server.ts
- packages/blade/docs/guides/BladeMCP.stories.mdx
> feat(blade-mcp): tweaks for non-dev personas

- packages/blade/src/components/FormGroup/FormGroup.stories.tsx
- packages/blade/src/components/FormGroup/code.ts
Documentation for FormGroup pattern
> docs(FormGroup): add documentation

- .changeset/flat-hairs-love.md
- packages/blade/src/components/Amount/Amount.stories.tsx
- packages/blade/src/components/Amount/Amount.tsx
- packages/blade/src/components/Amount/__tests__/Amount.native.test.tsx
- packages/blade/src/components/Amount/__tests__/Amount.web.test.tsx
- packages/blade/src/components/Amount/__tests__/__snapshots__/Amount.native.test.tsx.snap
- packages/blade/src/components/Amount/__tests__/mock.ts
Resolves https://razorpay.atlassian.net/jira/software/c/projects/DSSUP/list?atlOrigin=eyJpIjoiMzllODMyZDVkNjVlNGE3NWIwMTc2ZGExMzhmNjFhOTkiLCJwIjoiaiJ9&filter=reporter%20%3D%20%2261bc4362ef5b460071261b1a%22&selectedIssue=DSSUP-169
> feat(Amount): expose fractionDigits to consumers

- .changeset/friendly-rules-admire.md
- .changeset/green-eels-occur.md
- packages/blade-mcp/knowledgebase/Card.md
- packages/blade/src/components/Card/Card.stories.tsx
- packages/blade/src/components/Card/Card.tsx
> feat(Card): add maxWidth property to card

- packages/blade/src/components/CreationView/CreationView.stories.tsx
current example seems to be broken
> chore: update creation view stackblitz example

- .changeset/spotty-lies-argue.md
- packages/blade/src/components/Typography/Heading/Heading.tsx
> feat(Heading): add medium weight

- .changeset/giant-snakes-cheat.md
- packages/blade-mcp/knowledgebase/Modal.md
- packages/blade-mcp/knowledgebase/Preview.md
> chore: update knowledge base

- packages/blade/src/components/CreationView/CreationView.stories.tsx
- packages/blade/src/utils/storybook/StoryPageWrapper.tsx
> feat: add view  storybook file button

- .changeset/breezy-ravens-sniff.md
- .github/workflows/release.yml
> ci: update release.yml

- .changeset/wise-ads-invite.md
- packages/blade-mcp/knowledgebase/SideNav.md
> feat(SideNav): add default position note in knowledgebase

- .changeset/fast-olives-cheer.md
- packages/blade/src/components/ListView/types.ts
fix: update types for ListView
> fix: update types for ListView 

- .changeset/fast-lemons-hide.md
- packages/blade/rollup.config.mjs
- packages/blade/scripts/generateDocsLockFile.mjs
Description: https://github.com/razorpay/blade/pull/2715#discussion_r2104467191
> fix: build script for node 22

- .changeset/cool-stingrays-sip.md
- packages/blade/src/components/DatePicker/DatePicker.stories.tsx
- packages/blade/src/components/DatePicker/FilterChipDatePicker/DatePickerFilterChip.web.tsx
- packages/blade/src/components/Dropdown/FilterChipSelectInput.web.tsx
- packages/blade/src/components/Dropdown/docs/DropdownWithFilterChip.stories.tsx
- packages/blade/src/components/FilterChip/BaseFilterChip.web.tsx
- packages/blade/src/components/FilterChip/types.ts
was checking filterchip, it should support disabled prop. might have missed it.
> fix: add disabled prop in filterchip

- .changeset/chatty-grapes-allow.md
- packages/blade/src/components/Table/__tests__/Table.web.test.tsx
- packages/blade/src/components/Table/__tests__/__snapshots__/Table.web.test.tsx.snap
- packages/blade/src/components/Table/commonStyles/tableBodyStyles.tsx
Fixes row not being highlighted on selection
> fix(table): fix table selected styles

- .changeset/dull-trains-cheer.md
- .github/workflows/blade-validate.yml
- package.json
- packages/blade/package.json
- yarn.lock
> revert: "chore: update dependencies and improve CI workflow"

- .cursor/rules/component-review-checklist.mdc
> feat(.cursor/rules): add component review rule

- .changeset/few-pillows-lie.md
- packages/blade-mcp/src/tools/createBladeCursorRules.ts
- packages/blade-mcp/src/tools/createNewBladeProject.ts
- packages/blade-mcp/src/tools/getBladeComponentDocs.ts
- packages/blade-mcp/src/tools/getBladeGeneralDocs.ts
- packages/blade-mcp/src/tools/getBladePatternDocs.ts
Pass directory name to analytics
> feat(blade-mcp): pass directory name to analytics

- .changeset/dry-islands-remain.md
- packages/blade-mcp/knowledgebase/components/InputGroup.md
- packages/blade-mcp/knowledgebase/components/TextInput.md
> docs: trimmed knowledgebase for inputgroup and textinput

- packages/blade/src/components/InputGroup/docs/InputGroup.stories.tsx
> fix(inputgroup): storybook figma link

- .changeset/gentle-impalas-accept.md
we don't need changeset to update stories
> fix: remove changeset

- .changeset/violet-guests-whisper.md
- packages/blade-mcp/knowledgebase/components/EmptyState.md
> docs: add EmptyState in  knowledgebase

- .cursorignore
- .github/workflows/blade-validate.yml
> chore: update action to find and replace comment

- .changeset/metal-rocks-sell.md
- packages/blade/src/components/DatePicker/useDatesState.ts
prod - 
https://github.com/user-attachments/assets/fddde2db-7acd-4fe4-9567-ef20c8c73b87
dev - 
https://github.com/user-attachments/assets/d1a5bb09-997f-40cd-a9bf-185eb8370f09
> fix: month picker issue

- .changeset/plenty-poets-return.md
- packages/blade-mcp/src/tools/getChangelog.ts
> chore: changelog tool prompt

- .changeset/smooth-chefs-yell.md
- packages/blade/src/components/Alert/__tests__/__snapshots__/Alert.ssr.test.tsx.snap
- packages/blade/src/components/Button/BaseButton/__tests__/__snapshots__/BaseButton.native.test.tsx.snap
- packages/blade/src/components/Button/BaseButton/__tests__/__snapshots__/BaseButton.web.test.tsx.snap
- packages/blade/src/components/Button/BaseButton/buttonTokens.ts
- packages/blade/src/components/Button/Button/__tests__/__snapshots__/Button.native.test.tsx.snap
- packages/blade/src/components/Button/Button/__tests__/__snapshots__/Button.web.test.tsx.snap
- packages/blade/src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.web.test.tsx.snap
- packages/blade/src/components/SpotlightPopoverTour/__tests__/__snapshots__/Tour.web.test.tsx.snap
REF - 
[dev rev link](https://app.devrev.ai/razorpay/works?quickAccessId=don%3Acore%3Advrv-in-1%3Adevo%2F2sRI6Hepzz%3Avista%2F638&vista_view_type=list&group_by=stage&owned_by=don%3Aidentity%3Advrv-in-1%3Adevo%2F2sRI6Hepzz%3Adevu%2F8864&owned_by_op=any&stage=Acknowledged%2CNeeds+Clarity%2CTODO%2Cwork_in_progress%2Cawaiting_product_assist%2Cawaiting_development%2Cin_development%2Cawaiting_customer_response%2CDesign+-+In+Progress%2CDev+-+In+Progress%2Cqueued&subtype=dss%2Cjjuvewk7ojqvu33sobqvsltborygc43tnfqy4ltomx2f6mjrg44davzrge2tknw%2Cjjuvewk7ojqvu33sobqvsltborygc43tnfqy4ltomx2f6mjrg44davzrgawdcnw%2Cjjuvewk7ojqvu33sobqvsltborygc43tnfqy4ltomx2f6mjrg44davzrge2tkoa%2Cjjuvewk7ojqvu33sobqvsltborygc43tnfqy4ltomx2f6mjrg44davzrge3danq%2Cjjuvewk7ojqvu33sobqvsltborygc43tnfqy4ltomx2f6mjrg44davzrgawdcm …
> fix: text sizes in button

- .changeset/stale-rabbits-protect.md
- packages/blade-mcp/knowledgebase/components/Carousel.md
- packages/blade/src/components/Carousel/Carousel.stories.tsx
- packages/blade/src/components/Carousel/Carousel.web.tsx
- packages/blade/src/components/Carousel/CarouselItem.web.tsx
- packages/blade/src/components/Carousel/__tests__/__snapshots__/Carousel.web.test.tsx.snap
- packages/blade/src/components/Carousel/types.ts
> feat(carousel): added peek 

- .changeset/fresh-maps-check.md
- packages/blade-mcp/knowledgebase/components/ListView.md
- packages/blade/src/components/ListView/ListViewFilters.web.tsx
- packages/blade/src/components/ListView/docs/ListView.stories.tsx
- packages/blade/src/components/ListView/types.ts
> feat: add support for dropdown in search

- packages/blade-mcp/README.md
> chore: update mcp readme

- .changeset/new-kings-dress.md
- packages/blade-mcp/knowledgebase/components/Checkbox.md
> fix: add correct function definition for checkbox onchange (ISS-896326)

- .changeset/cyan-timers-yell.md
- packages/blade/src/components/Table/Table.web.tsx
- packages/blade/src/components/Table/__tests__/__snapshots__/Table.web.test.tsx.snap
> fix: table header sticky

- .changeset/nice-snakes-glow.md
- packages/blade/src/utils/usePaymentCardDetection.tsx
> fix(inputgroup): payment card icon jsx error

- .changeset/moody-tigers-design.md
- packages/blade/src/components/Carousel/Carousel.stories.tsx
> fix(carousel): resolve Storybook interaction issues in peek mode

- .changeset/orange-chefs-kick.md
- packages/blade/src/components/BottomSheet/BottomSheet.stories.tsx
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/components/BottomSheet/BottomSheetHeader.web.tsx
> fix: bottom sheet height logic

- .changeset/slow-tips-sleep.md
- packages/blade/src/components/Carousel/Carousel.stories.tsx
- packages/blade/src/components/Carousel/Carousel.web.tsx
- packages/blade/src/components/Carousel/constants.ts
- packages/blade/src/components/Carousel/types.ts
> feat: add new side navigation button option "overlap" in carousel

- .changeset/good-knives-listen.md
- packages/blade/src/components/DatePicker/utils.ts
> fix(datepicker): changed arrow to en dash in range input field

- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/components/BottomSheet/BottomSheetHeader.web.tsx
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.web.test.tsx
- packages/blade/src/components/BottomSheet/__tests__/__snapshots__/BottomSheet.web.test.tsx.snap
- packages/blade/src/components/Input/PhoneNumberInput/CountrySelector.web.tsx
> fix: add pseudo-element element height in bottom sheet , code refactor and tests

- .changeset/rotten-clocks-roll.md
- packages/blade/src/components/DatePicker/BaseDatePicker.web.tsx
- packages/blade/src/components/DatePicker/DateInput.web.tsx
- packages/blade/src/components/DatePicker/utils.ts
> feat(datepicker): added partial validation

- .changeset/cuddly-pigs-explode.md
- packages/blade-mcp/knowledgebase/components/DatePicker.md
- packages/blade/src/components/DatePicker/BaseDatePicker.web.tsx
- packages/blade/src/components/DatePicker/CalendarFooter.web.tsx
- packages/blade/src/components/DatePicker/DatePicker.stories.tsx
- packages/blade/src/components/DatePicker/_decisions/decisions.md
- packages/blade/src/components/DatePicker/types.ts
> feat(datepicker): exposing footer prop

- .cursor/rules/bi-weekly-announcement.mdc
feat: add bi weekly announcement cursor rule
> feat: add bi weekly announcement cursor rule

- .changeset/late-pumas-sell.md
- packages/blade-mcp/knowledgebase/components/BottomSheet.md
- packages/blade-mcp/knowledgebase/components/Modal.md
- packages/blade/src/components/BottomSheet/BottomSheet.native.tsx
- packages/blade/src/components/BottomSheet/BottomSheet.stories.tsx
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/components/BottomSheet/BottomSheetBackdrop.native.tsx
- packages/blade/src/components/BottomSheet/BottomSheetBackdrop.web.tsx
- packages/blade/src/components/BottomSheet/BottomSheetCloseButton.tsx
- packages/blade/src/components/BottomSheet/BottomSheetCommon.tsx
- packages/blade/src/components/BottomSheet/BottomSheetContext.ts
- packages/blade/src/components/BottomSheet/BottomSheetHeader.native.tsx
- packages/blade/src/components/BottomSheet/BottomSheetHeader.web.tsx
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.web.test.tsx
- packages/blade/src/components/BottomSheet/__tests__/__snapshots__/BottomSheet.native.test.tsx.snap
- packages/blade/src/components/BottomSheet/types.ts
- packages/blade/src/components/Modal/Modal.web.tsx
- packages/blade/src/components/Modal/ModalBackdrop.tsx
- packages/blade/src/components/Modal/ModalContext.tsx
- packages/blade/src/components/Modal/ModalHeader.web.tsx
- packages/blade/src/components/Modal/docs/ModalExamples.stories.tsx
- packages/blade/src/components/Modal/docs/SimpleModal.stories.tsx
- packages/blade/src/components/Modal/docs/stories.ts
- packages/blade/src/components/Modal/types.ts
feat: add non dismissible modal #2945
> feat: add non dismissible modal & bottomsheet

- packages/blade-mcp/README.md
> docs(blade-mcp): add one click cursor installer for blade-mcp

- .changeset/witty-badgers-admire.md
- packages/blade-mcp/knowledgebase/components/Modal.md
Added important constraints for ModalHeader's trailing prop.
> chore(blade-mcp): Update Modal.md with important constraints
