razorpay/blade

- .eslintrc.js
Components like TextInput has a lot of conditions but eslint has a restriction on the complexity of an arrow function which in our case is a React Component. Can We turn this rule off?
> chore(eslint): turn off complexity linting

- .babelrc.js
- package.json
with Jest 24 and Babel 7, need not to set modules
> fix(test): remove modules

- src/molecules/BottomSheet/BottomSheet.native.js
- src/molecules/BottomSheet/BottomSheet.stories.js
- src/molecules/BottomSheet/BottomSheetFooter.native.js
- src/molecules/BottomSheet/__tests__/BottomSheet.native.test.js
- src/molecules/BottomSheet/__tests__/__snapshots__/BottomSheet.native.test.js.snap
1. Calculates content height based on footer height when `adjustToContentHeight` prop is true. 
2. Disables the gradient effect when `adjustToContentHeight` is true.
3. Removes FooterComponent prop from test cases(my bad, wonder why did I leave it completely unnoticed!)
> fix(native/bottomsheet): update content height based on footer

- src/atoms/TextInput/TextInput.web.js
Getting an error when running tests on OnboardingRevamp. Need to check if it is due to the missing check for ref.current before accessing its style property.
> fix(TextInput): check inputRef.current inside useEffect

- .babelrc.js
- package.json
- src/atoms/TextArea/__tests__/__snapshots__/TextArea.web.test.js.snap
- src/atoms/TextInput/TextInput.web.js
- src/atoms/TextInput/__tests__/__snapshots__/TextInput.web.test.js.snap
- yarn.lock
Increase specificity for the placeholder style as this code https://github.com/razorpay/dashboard/blob/master/web/css/rzp/layout.styl#L406 is overriding the placeholder styles otherwise.
> fix(TextInput/react): increase specificity for placeholder style

- src/molecules/Amount/Amount.native.js
- src/molecules/Amount/__tests__/__snapshots__/Amount.native.test.js.snap
In android, Amount text was started from top but it should be vertically center just like iOS. Found that It is
working fine if we add _lineHeight to the fractionPart text. So, I have applied changes in it.
fix #239
Before:
After(With This change):
> fix(Amount/native): amount text should be vertically center

- ios/Podfile.lock
- jest-setup.native.js
- package.json
- src/icons/UploadCloud/UploadCloud.native.js
- src/icons/UploadCloud/UploadCloud.web.js
- src/icons/UploadCloud/index.js
- src/icons/index.js
- src/molecules/FileUpload/FileUpload.native.js
- src/molecules/FileUpload/FileUpload.stories.js
- src/molecules/FileUpload/FileUpload.web.js
- src/molecules/FileUpload/ProgressBar.native.js
- src/molecules/FileUpload/__tests__/FileUpload.native.test.js
- src/molecules/FileUpload/__tests__/__snapshots__/FileUpload.native.test.js.snap
- src/molecules/FileUpload/index.js
- storybook/native/main.js
- yarn.lock
- Props for File Upload Component
```
{
progress: number, // to indicate the progress of the upload
title: string, 
file: string, // file name
accept: array, // Accepts: ["allFiles", "audio", "csv", "doc", "docx", "images", "pdf", "plainText", "ppt", "pptx", "video", "xls", "xlsx", "zip"]
errorText: string,
helpText: string,
onError: func, // Callback is called when the native module is not able to pick the file
onFileUpload: func, // Callback is called when file is successfully picked by native module,
onRemove: func, //callback when user clicks on cross icon
}
```
- Currently Progress Bar component resides within FileUpload Component, will move it to separate component once the APIs are finalized.
- ProgressBar Pops 
```
{
color: "", // color of the progress bar[blade colors]
error: …
```
> feat(native/FileUpload): add Native FileUpload component

- src/molecules/Snackbar/Snackbar.native.js
On Android even if snackbar is not visible, Its content still remains on foreground. This is creating issue for the content which is at bottom on the screen. Users are unable to click whatever is behind the snackbar(even if snackbar is hidden).
<div style={{padding:"100px",alignItems:"center",display:"flex"}} >
</div>
> fix(Snackbar): remove content on hiding snackbar

- .eslintrc.js
This PR fixes 2 things:
1. The eslint rules for object curly conflicts with prettier and then the editor fights and errors out hence removed it. 
2. The prettier plugin was not configured properly to work with eslint
> chore(eslint): remove rules that conflicts with prettier

- .changeset/spotty-islands-do.md
- packages/blade-old/src/molecules/Amount/Amount.native.js
Amount component had default `lineHeight` of `xxlarge` when `size='xsmall'` which should be `small` (in sync with `Text` component behaviour)
Add case for `xsmall` in `lineHeight` function
Before
After
> fix(amount.native): Add missing lineHeight case when size='xsmall'

- packages/blade-old/src/icons/Download/Download.native.js
- packages/blade-old/src/icons/Download/Download.web.js
- packages/blade-old/src/icons/Download/index.js
- packages/blade-old/src/icons/index.js
Adds `download` icon for `payment gateway` feature.
> feat(blade-old): add download icon

- .changeset/gold-lies-divide.md
- packages/blade-old/src/atoms/Link/Link.native.js
- packages/blade-old/src/atoms/Link/__tests__/Link.native.test.js
- packages/blade-old/src/atoms/Link/__tests__/__snapshots__/Link.native.test.js.snap
This PR adds `weight` support in the native `<Link />` component. By default, the `weight` is `regular`.
Recently, for a feature I was working on, a bold web link was there in design like in the screenshot below and there is no way to add `weight` in `<Link />` as of now. Hope this PR solves the use case.
<details>
<summary>Usage</summary>
</details>
1. Regular weight by default
```
<Link onClick={navigateToWebDashboard} size="medium" testID="web-dashboard-link">
web dashboard
</Link>
```
2. `<Link />` with `light` weight
```
<Link weight="light" onClick={navigateToWebDashboard} size="medium" testID="web-dashboard-link">
web dashboard
</Link>
```
3. `<Link />` with `bold` weight
```
<Link weight="bold" onClick={navigateToWebDashboard} size="medium" testID="web-dashboard-link">
web …
```
> feat(blade-old): add weight support in Link native component

- .changeset/mighty-cars-explode.md
- packages/blade-old/package.json
- yarn.lock
The PG mobile is on react native v0.65, in which the API of keyboard listeners has changed.
The `react-native-modalize` package which is a dependency of `blade-old` also uses keyboard listeners internally.
This PR updates the `react-native-modalize` support for RN v0.65 and above.
> fix(blade-old): updated support of  rn-modalize for RN v0.65

- .changeset/sharp-dragons-hope.md
- packages/blade-old/package.json
The `scripts` directory was not added to `files` array in `package.json` and hence was not getting published to npm. As a side-effect of this the migration to new version just broke because the it the command was unable to locate the codemod script.
> fix(blade-old): include scripts while publishing

- .changeset/quiet-impalas-explain.md
- packages/blade-old/scripts/icon-migrate-codemod/transforms/blade-old-icon.ts
While migrating razorpay mobile app repo, folks found issues with the codmod, this PR addresses two issues: 
- Fixes dangling import which is being added on every file
- Fixes CLI unable to change parser type to TSX
> fix(blade-old): icon migrate script dangling imports

- .changeset/dull-vans-ring.md
- packages/blade-old/package.json
- packages/blade-old/src/molecules/Modal/Modal.native.js
- packages/blade-old/src/molecules/Modal/__tests__/__snapshots__/Modal.native.test.js.snap
- yarn.lock
Description
Update react-native-modal to v13.0.0
Fixes
- Remove usage of `EventEmitter.removeListener()` deprecated API
- Add `useNativeDriverForBackdrop` to fix backdrop flicker issue on modal dismissal.
> feat(Modal): Migrate react-native-modal to 13.0.0

- package.json
add `preinstall` script since a lot of npm packages use `git://github.com/CharlesMangwa/simple-markdown.git` in their dependencies and because there's an EOL for [`git` protocol](ofhttps://github.blog/2021-09-01-improving-git-protocol-security-github/) the installations start failing since we have couple of downstream packages as well. So adding the git config as a preinstall script which will force the git to use `https` whenever it finds `git` while installing packages.
> fix(blade): add `preinstall` script to set `https` protocol instead of `git`

- package.json
Fixes the failing CI while installing node dependencies
> build: make git config global to set `https` protocol instead of `git`

- packages/blade/docs/tokens/Border.stories.mdx
- packages/blade/docs/tokens/Breakpoints.stories.mdx
- packages/blade/docs/tokens/Colors.stories.mdx
- packages/blade/docs/tokens/Spacing.stories.mdx
- packages/blade/docs/tokens/Typography.stories.mdx
Fix storybook build failing leading to chromatic deployment failing.
This originated here: https://github.com/razorpay/blade/pull/442
> fix: storybook build

- packages/blade/src/components/Typography/BaseText/BaseText.stories.tsx
- packages/blade/src/components/Typography/BaseText/BaseText.tsx
- packages/blade/src/components/Typography/Heading/Heading.tsx
- packages/blade/src/components/Typography/Text/Text.tsx
- packages/blade/src/components/Typography/Title/Title.tsx
- packages/blade/src/components/Typography/_decisions/decisions.md
This PR streamlines the type of children that each component of the `Typography` family accepts. Here are the decisions that were taken:
`children: React.ReactNode`
* Children are mandatory
* We could accept any valid ReactNode which is one of `ReactElement | ReactText | ReactFragment | ReactPortal | boolean | null | undefined`.
* The reason to accept `ReactNode` for `BaseText` is since this is a raw structure for the consumers they can satisfy their use case of building anything custom for rare use cases. For example, composing BaseText components by nesting them to make one word bold in a sentence. 
```
<BaseText>
<BaseText weight="bold">Current <BaseText/>
Accounts supercharged by RazorpayX come with integrated tools and integrations that make financial management and accounting simple …
```
> fix(blade): make children prop across Typography suite better

- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/src/components/Button/Button/Button.stories.tsx
- packages/blade/src/components/SkipNav/SkipNav.stories.tsx
- packages/blade/src/components/Typography/BaseText/getBaseTextStyles.ts
Renders similarly on native but ignores story descriptions
**Web:**
**Native:**
> feat: add button stories

- packages/blade/.storybook/react/manager.js
This addon will provide ability to hide and show internal components in storybook. 
Just prefix any story name with `Internal` and it will be handled by this addon. 
You can also prefix a single story component to be internal by changing the exported story's name. 
> NOTE: Storybook doesn't provide a way for us to hide [stories from sidebar](https://github.com/storybookjs/storybook/issues/9209) thus had to use CSS workaround.
https://user-images.githubusercontent.com/35374649/176144599-4ee5e51e-edf2-403c-840b-511fd3083016.mov
> feat(blade): added InternalStoryAddon

- packages/blade/docs/guides/Intro.stories.mdx
Replaced the `phases of DS` image towards the end of the file.
> Updated the phases of DS image to latest stage

- .changeset/early-mayflies-retire.md
- packages/blade-old/src/atoms/Checkbox/Checkbox.native.js
- packages/blade-old/src/atoms/Checkbox/Checkbox.web.js
The `<Checkbox />` component in `blade-old` gave the following unnecessary warning whenever we passed `size="small"` to it.
These used to come even if didn't pass these _optional_ props to `<Checkbox />` but passed `size` as "small".
For eg, using `<Checkbox />` as below gave an error in console & unit tests.
```jsx
<Checkbox
testID="whatsapp-checkbox"
size="small"
title={translate('contactDetails.whatsappOptinCheckboxTitle')}
checked={checked}
onChange={onChange}
disabled={disabled}
/>
```
1. Warning for `helpText`
```
console.error
Warning: Failed prop type: [helpText]. helpText is ignored as it is not supported when size is small in Checkbox
at Checkbox (/Users/ayush.gupta/Documents/rzp/pr-reviews/pr-frontend-mobile-app/node_modules/@razorpay/blade-old/src/atoms/Checkbox/Checkbox.native …
```
> fix(blade-old): remove unnecessary warning for `Checkbox` props

- packages/blade/src/components/Button/Button/Button.stories.tsx
Since we're since some incorrect usage of Icon with Buttons, wanted to try and enhance the story a bit to be clearer on how to use these icons. Not sure if this will have any impact at all but better this than nothing for now. 
**Before:**
**After:**
> chore: improve the button story with icons to show proper usage

- .github/dependabot.yml
Only security updates will happen now
- [Docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit)
> infra: disable dependabot version update PRs

- packages/blade/src/components/Icons/_Svg/Path/Path.d.ts
- packages/blade/src/components/Icons/_Svg/Path/Path.native.tsx
- packages/blade/src/components/Icons/_Svg/Path/Path.web.tsx
- Adds an Exact<> type which will fix the edge cases in SVG Path props
> chore: fix path exact types

- packages/blade/docs/guides/Installation.stories.mdx
Was testing out Blade on CRA, adds a missing step in installation
> docs(Installation): add styled-components as dependency

- .changeset/wild-ghosts-bake.md
- packages/blade-old/src/atoms/TextInput/CharacterCount.native.js
- packages/blade-old/src/atoms/TextInput/Text.native.js
- The text fields in pg-mobile app have helper text, character counter They are currently unreadable due to the font size and poor contrast.
- We have changed the helper text & character counter color value from `shade.950` to `shade.960`
- For disabled state color value changed from `shade.930` to `shade.940`
- This [document](https://docs.google.com/document/d/1qkblBEpZ7UZtpYF-5rGuYl1RI6joFeGbr13w4E614UU/edit) has the screenshots which are showing the changes for both pg-mobile and x-mobile app.
- [Slack thread](https://razorpay.slack.com/archives/C01HD2D4U14/p1660030157149279)
[SSAB-343](https://razorpay.atlassian.net/browse/SSAB-343)
> changed native text-input helptext color to improve contrast

- .github/workflows/blade-validate.yml
- packages/blade/src/components/Form/FormLabel.tsx
- packages/blade/src/components/Form/FormTypes.ts
- packages/blade/src/components/Form/index.ts
- packages/blade/src/components/Input/BaseInput/BaseInput.tsx
- packages/blade/src/components/Input/TextInput/TextInput.tsx
- yarn.lock
Issue: aliased imports from `~components/Form` breaks the type generation
Workaround(not ideal but unblocking release for now): replace alias imports with relative imports `~components/Form` ➡️ `../../Form`
> fix: TextInput imports

- CONTRIBUTING.md
- packages/blade/package.json
Added npm scripts that are a bit easier to remember. Now single commands like `yarn start:ios` and `yarn start:android` can run emulator and server both.
Also added `yarn start:all` to run everything everywhere and `yarn start:native` to run android and ios at the same time.
> feat: add easier to remember npm scripts

- packages/blade/src/components/Typography/_decisions/decisions.md
In implementation, I can see we're using `body | caption` instead of `medium | large | caption`. In decisions it doesn't seem updated so added it here. Need to confirm with Kamlesh if that is expected.
Mostly the previous decisions look good to me. I've only changed `variant` prop to `size` and changed value from `caption` to `medium` because that is what I see on Figma file. Don't see `caption` variant anywhere there.
> feat(Code): update API decisions for `Code` and `Text`

- .changeset/spicy-mails-doubt.md
- packages/blade/src/components/Input/BaseInput/StyledBaseInput.web.tsx
- packages/blade/src/components/Input/BaseInput/__tests__/__snapshots__/BaseInput.web.test.tsx.snap
- packages/blade/src/components/Input/PasswordField/__tests__/__snapshots__/PasswordField.web.test.tsx.snap
- packages/blade/src/components/Input/TextArea/__tests__/__snapshots__/TextArea.web.test.tsx.snap
- packages/blade/src/components/Input/TextInput/__tests__/__snapshots__/TextInput.web.test.tsx.snap
| PasswordField | TextInput |
| - | - |
|  <img width="1512" alt="Screen Shot 2022-09-22 at 13 00 43" src="https://user-images.githubusercontent.com/6682655/191685738-880ba662-2393-43e6-807a-d19e9ef5ef9f.png"> | <img width="1512" alt="Screen Shot 2022-09-22 at 13 00 57" src="https://user-images.githubusercontent.com/6682655/191685773-3e9b1a6e-5fec-43ec-850a-7024e378d374.png"> |
> fix(BaseInput): use cursor not-allowed for disabled inputs

- .gitignore
- .vscode/settings.json
Adds vscode settings with import exclusions. 
So we get the benefit of [TS4.8 auto exclude imports ](https://devblogs.microsoft.com/typescript/announcing-typescript-4-8/#exclude-globs-auto-import)
> chore: add vscode settings import exclusions

- .changeset/five-tomatoes-try.md
- packages/blade/src/components/Alert/Alert.tsx
- packages/blade/src/components/Typography/Heading/Heading.stories.tsx
- packages/blade/src/components/Typography/Heading/Heading.tsx
- packages/blade/src/components/Typography/Heading/__tests__/Heading.native.test.tsx
- packages/blade/src/components/Typography/Heading/__tests__/Heading.web.test.tsx
- packages/blade/src/components/Typography/Heading/__tests__/__snapshots__/Heading.native.test.tsx.snap
- packages/blade/src/components/Typography/Heading/__tests__/__snapshots__/Heading.web.test.tsx.snap
- packages/blade/src/components/Typography/Title/Title.stories.tsx
- packages/blade/src/components/Typography/Title/Title.tsx
- packages/blade/src/components/Typography/Title/__tests__/Title.native.test.tsx
- packages/blade/src/components/Typography/Title/__tests__/Title.web.test.tsx
> **Warning**
>
> Breaking Change. Changes the prop names and values in some Typography components.
Slack Discussion - https://razorpay.slack.com/archives/G01B3LQ9H0W/p1663325670139239?thread_ts=1663318580.283669&cid=G01B3LQ9H0W
Currently the API for typography components is not consistent with each other. For e.g. - 
```jsx
<>
<Title variant="medium">Medium Title</Title>
<Heading variant="small">Small Heading</Heading>
<Text size="small">Small Text</Text>
</>
```
As you can see some component use `variant` for deciding the size whereas `Text` uses `size`.
- In `Title`: Rename `variant` to `size`
- In `Heading`: Add `variant="regular"` and add size with `small | medium | large` type
All typography components will now use `size` prop for deciding the size. 
```jsx
<>
<Title …
```
> feat(Typography)!: make `Heading`, `Title`, and `Text` API consistent

- packages/blade-old/src/atoms/Link/Link.stories.js
Some Security semgrep check is failing on master. I am ignoring it for now since it's just a storybook file and that too from old blade repo.
Removed the `@ts-expect-error` because there isn't any TS error on that file so don't think so we need it anymore
> fix(Link.stories.js): ignore semgrep on Link stories

- .changeset/tall-garlics-change.md
- packages/blade/src/components/Link/BaseLink/BaseLink.tsx
- packages/blade/src/components/Link/BaseLink/__tests__/__snapshots__/BaseLink.native.test.tsx.snap
- packages/blade/src/components/Link/BaseLink/__tests__/__snapshots__/BaseLink.web.test.tsx.snap
- packages/blade/src/components/Link/BaseLink/types.ts
- packages/blade/src/components/Link/Link/Link.stories.tsx
- packages/blade/src/components/Link/Link/Link.tsx
- packages/blade/src/components/Link/Link/__tests__/Link.native.test.tsx
- packages/blade/src/components/Link/Link/__tests__/Link.web.test.tsx
- packages/blade/src/components/Link/Link/__tests__/__snapshots__/Link.native.test.tsx.snap
- packages/blade/src/components/Link/Link/__tests__/__snapshots__/Link.web.test.tsx.snap
- packages/blade/src/components/Link/_decisions/decisions.md
- Adds a new `size` prop that is medium by default but can accept a small value too.
- BaseLink updated to the same.
- Also fixes an inconsistency where icon only links would appear slightly larger in size. Now matches the design behavior.
> **Warning**
>
> Because of how this affects icons in links the icons would appear slightly bumped up in size now
| ios | android |
| - | - |
| ![Simulator Screen Shot - iPhone 13 - 2022-10-19 at 18 07 46](https://user-images.githubusercontent.com/6682655/196695663-ec60c583-5d81-4490-9d34-765f9d6ce4b6.png) | ![Screenshot_1666183364](https://user-images.githubusercontent.com/6682655/196695738-90cfb9e3-a392-4434-b23b-74a2eda3ae8d.png) |
- [Figma](https://www.figma.com/file/jubmQL9Z8V7881ayUD95ps/Blade---Payment-Light?node-id=12699%3A147155)
- …
> feat(Link): add size small

- .github/workflows/release.yml
- package.json
Currently we are publishing to public npm registry on every commit to master. 
We only should publish it when we merge the builder version PRs.
> fix: npm releases with changeset

- packages/blade/.storybook/react/manager.js
- packages/blade/.storybook/react/preview.js
resolves #626 
- Updates the stylesheet for `internal components` in the preview `iframe`( `preview.js` is used to render stories ) as well based on the global variable `showInternalComponents` value.
> fix: show internal stories in docs

- .github/workflows/release.yml
- README.md
- packages/blade/docs/guides/Installation.stories.mdx
- packages/blade/docs/guides/Intro.stories.mdx
- packages/blade/docs/guides/LocalDevelopment.stories.mdx
- packages/blade/package.json
- packages/blade/scripts/publish-to-npm.js
**Changes**
- Move README from root to blade package while publishing and remove after publishing
- Updated the installation guide, and some minor text in our storybook docs according to changes after npm registry publish. (Added comments below with reasoning)
Fixes #762
> feat: add README to npm

- packages/blade/src/_helpers/storybook/FigmaEmbed.tsx
- packages/blade/src/components/Badge/Badge.stories.tsx
Adds figma embed integration to Storybook.
```jsx
import FigmaEmbed from '~src/_helpers/storybook/FigmaEmbed';
// ...
<FigmaEmbed title="Badge Figma Design" src={figmaURL} />
```
Can be used with `useMakeFigmaURL` to add theming support. Check this diff in this PR :D
Try it out here - https://61c19ee8d3d282003ac1d81c-ognnptlqpg.chromatic.com/?path=/docs/components-badge--badge
https://user-images.githubusercontent.com/30949385/199401012-aea03e57-3e6d-4c38-8865-7906e2a18959.mov
- Add support for other components (This PR only adds support to `Badge.stories` to keep the diff minimal). Will be adding this in follow up PRs later.
> feat(FigmaEmbed): add Figma Embed integration to Storybook

- packages/blade/.storybook/react/manager.js
- packages/blade/.storybook/react/preview.js
- packages/blade/docs/guides/Installation.stories.mdx
- packages/blade/docs/guides/Intro.stories.mdx
- packages/blade/docs/guides/LocalDevelopment.stories.mdx
- packages/blade/docs/guides/Usage.stories.mdx
- packages/blade/src/components/Alert/Alert.stories.tsx
- Changes the canvas background to background color token. So the background of stories now changes when we change theme.
- Some aesthetic improvements
Try changing themes here - https://61c19ee8d3d282003ac1d81c-brglhsqsoq.chromatic.com/?path=/story/guides-intro--page&globals=measureEnabled:false
> **Note**
>
> This changes the canvas so the chromatic requires approvals for all components. I will do that once the PR is approved.
Things were too cluttered in some places. Improved the spacings a bit. Also changed the intro page badges and some font sizes for the love of aesthetics.
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
https://user-images.githubusercontent.com/30949385/199931619-674f2609-1961-49e5-a73c-d9cd1dda6e5f.mov
> feat(storybook): add support for theming

- packages/blade/src/_helpers/storybook/Sandbox/Sandbox.web.tsx
- packages/blade/src/components/Alert/Alert.stories.tsx
- packages/blade/src/components/Button/Button/Button.stories.tsx
- packages/blade/src/components/Checkbox/Checkbox.stories.tsx
- packages/blade/src/components/Checkbox/CheckboxGroup.stories.tsx
- packages/blade/src/components/Counter/Counter.stories.tsx
- packages/blade/src/components/Input/OTPInput/OTPInput.stories.tsx
- packages/blade/src/components/Input/PasswordInput/PasswordInput.stories.tsx
- packages/blade/src/components/Input/TextArea/TextArea.stories.tsx
- packages/blade/src/components/Input/TextInput/TextInput.stories.tsx
- packages/blade/src/components/Link/Link/Link.stories.tsx
- packages/blade/src/components/Radio/Radio.stories.tsx
- packages/blade/src/components/SkipNav/SkipNav.stories.tsx
- packages/blade/src/components/Spinner/Spinner/Spinner.stories.tsx
- packages/blade/src/components/Typography/Code/Code.stories.tsx
- packages/blade/src/components/Typography/Heading/Heading.stories.tsx
- packages/blade/src/components/Typography/Text/Text.stories.tsx
- packages/blade/src/components/Typography/Title/Title.stories.tsx
- packages/blade/src/components/VisuallyHidden/VisuallyHidden.stories.tsx
In earlier integration PRs, I only made changes to `Badge` stories to keep the PRs focussed and small. This PR adds examples to all the rest of the components.
- Figma Integration #804 
- CodeSandbox Integration #803 
> **Note**
>
> The PR is large but it is repetitive code
> feat(storybook): add codesandbox examples and figma embed to all components

- .devcontainer/devcontainer.json
- packages/blade/src/components/Icons/Icons.stories.tsx
**Description**
Closes #669. This is what I came up with. When `icon` is set to `undefined` it shows all available icons with their respective names. To see individual icon, select option can be used. More at https://github.com/razorpay/blade/issues/669#issuecomment-1312676483.
> docs(Icons): add icon grid story

- .github/workflows/blade-chromatic.yml
- packages/blade/.storybook/react/main.js
- packages/blade/src/_helpers/storybook/Sandbox/Sandbox.web.tsx
Storybook Sandpack now uses the preview version deployed by codesandbox CI.
This will mean, if you add a new component that is not released yet. You will be able to preview that component as well in your storybook sandbox.
You can also run `GITHUB_SHA=<full commit sha of version of blade you want> yarn start:web` locally to use that version locally in your storybook.
> feat(Sandbox): use csb preview blade version in sb previews

- .github/workflows/blade-chromatic.yml
- packages/blade/.storybook/react/main.js
- packages/blade/src/_helpers/storybook/Sandbox/Sandbox.web.tsx
Sandpack is failing on master because we don't publish codesandbox ci preview version on master. This PR adds check that sets `*` version on master.
https://razorpay.slack.com/archives/G01B3LQ9H0W/p1668669020171609
> fix(Storybook): failing csb previews on master

- packages/blade/src/_helpers/storybook/FigmaEmbed.tsx
The figma is not accessible to external people right now. Added note for that.
Also the note was getting too large so shortened the note for adblockers as well.
> feat(FigmaEmbed): add access note for external people

- packages/blade/src/components/Button/IconButton/IconButton.stories.tsx
Since we're console logging on clicks it's a nice quality of life improvement to show console by default
> feat(IconButton.stories): show console by default

- packages/blade/src/components/Icons/Icons.stories.tsx
We often receive PRs for adding new icons. Adds some docs for reference.
See the [new docs here](https://61c19ee8d3d282003ac1d81c-ffzhqctgvz.chromatic.com/?path=/docs/components-icons--icon&globals=measureEnabled:false)
> docs(Icons): docs for adding new icons

- .github/workflows/blade-pr-title-check.yml
It was failing in #887 because CI_TOKEN is not accessible to people outside of Razorpay
> fix(blade-pr-title-check): use github token instead of ci token

- .changeset/friendly-oranges-decide.md
- packages/blade/src/components/Checkbox/Checkbox.tsx
- packages/blade/src/components/Checkbox/__tests__/Checkbox.web.test.tsx
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.web.test.tsx.snap
Currently, Checkbox only accepts `childern` of type `string`
but we have use cases where we may want to pass multiple elements, not just only string, as discussed in #787 
Resolves #787
> fix(Checkbox): allows Checkbox to accept `childern` prop of type `React.ReactNode`

- .changeset/cool-pandas-draw.md
- packages/blade/src/components/Input/OTPInput/OTPInput.stories.tsx
- packages/blade/src/components/Input/OTPInput/OTPInput.tsx
- packages/blade/src/components/Input/OTPInput/__tests__/OTPInput.native.test.tsx
- packages/blade/src/components/Input/OTPInput/__tests__/OTPInput.web.test.tsx
- packages/blade/src/components/Input/OTPInput/__tests__/__snapshots__/OTPInput.web.test.tsx.snap
- packages/blade/src/components/Input/OTPInput/_decisions/_decisions.md
Adds support for masked input fields in `OTPInput`
**Demo:** 
https://user-images.githubusercontent.com/24487274/204982587-e1400d43-7f01-4bc5-8b85-6072cdb473a9.mov
> feat: allow masked otp input

- .changeset/proud-boxes-reflect.md
- packages/blade/src/components/Alert/Alert.stories.tsx
- packages/blade/src/components/Alert/Alert.tsx
- packages/blade/src/components/Alert/__tests__/Alert.native.test.tsx
- packages/blade/src/components/Alert/__tests__/Alert.web.test.tsx
- packages/blade/src/components/Alert/__tests__/__snapshots__/Alert.native.test.tsx.snap
- packages/blade/src/components/Alert/__tests__/__snapshots__/Alert.web.test.tsx.snap
- packages/blade/src/components/Alert/_decisions/decisions.md
- packages/blade/src/components/Alert/styles.ts
- packages/blade/src/components/Alert/types.ts
Now `isFullWidth` prop is rewired to cause these effects:
- Makes the alert borderless (same UI as earlier with `isBorderless` on mobile and native)
- Makes the actions inline (appear horizontal) with the content besides the above change (only on desktop). Note that actions always appear vertically on mobile and react native.
Tested various combinations, some screenshots:
And... oh well, here's a meme 😅
> feat(Alert): update `isFullWidth` to make inline borderless alerts on desktop

- packages/blade/.storybook/react/constants.js
- packages/blade/.storybook/react/manager.js
- packages/blade/.storybook/react/preview.js
fixes https://github.com/razorpay/blade/issues/828
Previously storybook wasn't able to load the global variable `showInternalComponents` on initial load of the addon. Thus even when URL was shared with the global parameter storybook wasn't rendering the story.
> fix: storybook internal component addon

- packages/blade/docs/guides/Installation.stories.mdx
`--platform` is not a valid arg. `--platforms` is valid.
> docs: fix react-native link command

- packages/blade/docs/guides/Installation.stories.mdx
- packages/blade/src/components/Typography/Code/Code.tsx
- packages/blade/src/components/Typography/Code/__tests__/__snapshots__/Code.native.test.tsx.snap
- packages/blade/src/components/Typography/Code/__tests__/__snapshots__/Code.web.test.tsx.snap
changes the background color from gray.400 to gray.a50 
(we earlier went with `gray.400` because alpha shades were unavailable.
> feat(Code): use new alpha color in background

- packages/blade/src/components/Card/Card.tsx
- packages/blade/src/components/Card/CardContext.tsx
- packages/blade/src/components/Card/CardFooter.tsx
- packages/blade/src/components/Card/CardHeader.tsx
- packages/blade/src/components/Card/__tests__/Card.native.test.tsx
- packages/blade/src/components/Card/__tests__/Card.web.test.tsx
- packages/blade/src/components/Input/BaseInput/BaseInput.stories.tsx
This PR adds: 
- Restricted childrens components in Card to be one of CardHeader, CardBody, CardFooter
- Restricted childrens components in CardHeader to be one of CardHeaderLeading, CardHeaderTrailing
- Restricted childrens components in CardFooter to be one of CardFooterLeading, CardFooterTrailing
> fix(blade): restrict childrens in Card component

- .changeset/shaggy-pigs-warn.md
- packages/blade/src/components/Input/TextArea/TextArea.tsx
- packages/blade/src/components/Input/TextInput/TextInput.tsx
- packages/blade/src/components/Input/TextInput/__tests__/TextInput.native.test.tsx
- packages/blade/src/components/Input/TextInput/__tests__/TextInput.web.test.tsx
Fixes a bug where TextInput shows clear button even when showClearButton is false with initialValue set. 
Fixes: https://app.asana.com/0/1200620439276878/1203628642944573/f
> fix(blade): TextInput clear button state

- .changeset/chilled-radios-greet.md
- packages/blade/package.json
[Jira][1] | Fixes #957 
Users of Blade are forced to use the `--legacy-peer-deps` flag for installing packages because starting from v7, npm install fails if all peer dependencies specified by a package are not installed by the host project. This is a problem because this means Blade's peerDependencies config will force all web projects to install react-native unless they use the above flag.
Screenshot from the dashboard project:
The `peerDependenciesMeta` field of `package.json` is used for solving exactly this problem. This will inform npm that it needs to check the version of react-native peerDependencies of Blade only for projects that already have react-native installed on the host. 
Refer: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta
[1]: …
> fix: mark react-native dependencies as optional

- packages/blade/.storybook/react/preview.js
Right now if you visit `blade.razorpay.com` select a story & any story variants it will show you the `docs` page, but even if you select `story` tab and try navigating the stories it will redirect you to the `docs` tab, so to quickly check the story variants you need to each time select `story` tab. 
before: 
https://user-images.githubusercontent.com/35374649/214499131-bc72ac2b-8aaf-420e-ae36-0a13dbd9c734.mov
after: 
https://user-images.githubusercontent.com/35374649/214499499-67ecf93d-d2ce-4a91-9193-39cc11742634.mov
> chore: remove viewmode from storybook config

- packages/blade/.storybook/react/preview.js
- packages/blade/docs/guides/ComponentStatus.stories.mdx
- packages/blade/src/_helpers/storybook/ComponentStatusTable.tsx
- packages/blade/src/_helpers/storybook/LinkToStorybook.tsx
This PR adds component status table in storybook to show which components are ready/in-progress/planned
[Link to storybook](https://61c19ee8d3d282003ac1d81c-hhcipvslio.chromatic.com/?path=/docs/guides-component-status--page)
> chore: added component status table

- .changeset/pretty-swans-perform.md
- packages/blade/package.json
Fixes #960 
TypeScript requires types to be declared in the `"types"` property under `"exports"` section of `package.json` of npm packages to detect declaration files in a project setup that outputs ESM. 
(combination of `type:module` in project's `package.json` and `module:NodeNext` in `tsconfig.json`)
I've added the missing fields. These fields are only used by TypeScript in an ESM setup so backwards compatibility shouldn't be affected.
**Note:** An alternate shorter solution is to rename the generated types files for web from `index.d.ts` to `index.web.d.ts`. While that would work for the above config, it will break types for `moduleResolution:node`. Since the automatic detection of TypeScript varies based on the moduleResolution used, it's better to tell TypeScript explicitly where …
> fix: package types exports for ESM projects

- packages/blade/src/components/ActionList/ActionListItem.tsx
- packages/blade/src/components/Dropdown/Dropdown.tsx
- packages/blade/src/components/Dropdown/useDropdown.ts
- packages/blade/src/components/Input/BaseInput/BaseInput.tsx
- packages/blade/src/components/Input/BaseInput/StyledBaseInput.native.tsx
- packages/blade/src/components/Input/BaseInput/StyledBaseInput.web.tsx
- packages/blade/src/components/Input/BaseInput/types.ts
- packages/blade/src/components/Input/SelectInput/SelectInput.tsx
fixes #989 
- I passed `shouldIgnoreBlur` and `setShouldIgnoreBlur` to `BaseInput` so that we can ignore the blur event when we don't really want to call the blur out animation.
- ~I also removed the `triggererRef` from the Dropdown context because we only needed it to reput the focus on select which is not needed anymore as we just ignore the blur.~ We're only ignoring blur animation and not the blur itself so we still need to manage focus.
> fix(Dropdown): ignore flicker in Select when clicking items

- .codesandbox/ci.json
examples is moved inside packages now so the codesandbox CI was unable to detect the example while building. this should fix the preview codesandbox now.
> fix: codesandbox ci example URL

- packages/blade/src/_helpers/storybook/ComponentStatusTable.tsx
Added this component lifecycle so our consumers can understand what stage the component is in and what are the stages in between to release  it
> docs: add component lifecycle at the top of table

- packages/blade/src/_helpers/types.ts
- packages/blade/src/components/ActionList/ActionListItem.tsx
- packages/blade/src/components/Badge/Badge.tsx
- packages/blade/src/components/Button/BaseButton/BaseButton.tsx
- packages/blade/src/components/Button/Button/Button.stories.tsx
- packages/blade/src/components/Button/Button/Button.tsx
- packages/blade/src/components/Indicator/Indicator.tsx
- packages/blade/src/components/Link/BaseLink/BaseLink.tsx
- packages/blade/src/components/Link/Link/Link.tsx
- packages/blade/src/components/Radio/Radio.tsx
- packages/blade/src/components/SkipNav/SkipNav.native.tsx
- packages/blade/src/components/SkipNav/SkipNav.web.tsx
- packages/blade/src/components/Typography/Code/Code.tsx
- packages/blade/src/components/Typography/Heading/Heading.tsx
- packages/blade/src/components/Typography/Title/Title.tsx
- packages/blade/src/utils/getStringChildren/getStringChildren.ts
- packages/blade/src/utils/getStringChildren/index.ts
The following code now works with this PR-
```jsx
<Button>{someVariable} hello</Button>
```
Fixes the issue from this comment https://github.com/razorpay/blade/issues/811#issuecomment-1318289632
Slack Thread: https://razorpay.slack.com/archives/G01B3LQ9H0W/p1669028285672599
~Just changing it to `string | string[]` instead of `ReactText | ReactText[]` since we have several checks for strings which I didn't want to break.~ Changed it to `ReactText | ReactText[]`
> feat: support string array in children

- .changeset/two-carrots-provide.md
- packages/blade/package.json
The changes made in #970 caused Jest tests to [break][1] for Blade consumers.
This is because Jest [does not support][2] the "import" condition in package exports.
Proper support for the exports field for Jest is still an open issue:
https://github.com/browserify/resolve/issues/222
But we can fix this just by providing a "default" field which Jest does recognise. Since we're not exporting a dual package build which requires explicit `import`/`require` conditions, the default field is sufficient for all tools consuming Blade.
I've also moved the "types" to be defined first as is recommended by TypeScript. It still works right now in `master` because of a [bug in TypeScript][3]. Refer: https://arethetypeswrong.github.io/
[1]: https://razorpay.slack.com/archives/C02S42DDKU3/p1677557736749599 …
> fix: change import to default in package exports

- packages/blade/src/components/Dropdown/Dropdown.stories.tsx
- Adds missing properties for Select and ActionListItem to Dropdown stories
The documentation isn't very satisfactory to me right now. Let me fix it all when I am adding documentation for Button triggers and individual documentation of Select and ActionList.
> docs(Dropdown): add missing props from Select and ActionListItem

- packages/blade/docs/guides/IntegrationExamples.stories.mdx
Since we moved examples folder inside packages, the integration guide page on story book was pointing to the wrong path which was resulting in a broken experience.
> chore: fix wrong link in integration docs

- .changeset/yellow-countries-smoke.md
- packages/blade/src/components/Typography/Text/Text.tsx
- packages/blade/src/components/Typography/Text/__tests__/Text.native.test.tsx
- packages/blade/src/components/Typography/Text/__tests__/Text.web.test.tsx
- packages/blade/src/components/Typography/Text/__tests__/__snapshots__/Text.native.test.tsx.snap
- packages/blade/src/components/Typography/Text/__tests__/__snapshots__/Text.web.test.tsx.snap
Need to add textAlign support to center align text in certain cases on native
(ignore the other styling changes in screenshot, one is using blade components and other is without blade)
|  without  |  with |
| --- | --- |
| ![Simulator Screen Shot - iPhone 14 Pro - 2023-03-01 at 12 21 55](https://user-images.githubusercontent.com/24487274/223083771-5157b101-59ac-4c0a-9a70-bbbf663ab7a0.png) | ![Simulator Screen Shot - iPhone 14 Pro - 2023-03-01 at 12 18 41](https://user-images.githubusercontent.com/24487274/223083778-2b0d674a-9e0f-4d69-be5e-b6582b53e70f.png) |
> feat(Text): add `textAlign` prop

- .changeset/fifty-penguins-tickle.md
- .eslintrc.js
- packages/blade/src/utils/getStringChildren/getStringChildren.ts
This import was adding entire lodash bundle. There are some issues with tree-shaking which I am figuring out but this was a quickfix
> fix: lodash bundle-size

- packages/blade/src/components/Input/TextInput/__tests__/TextInput.web.test.tsx
We almost removed this test and disabled text input while loading. Adding comment in the test for future when someone tries to "fix" this too.
> test: add comment why TextInput is not disabled when loading

- .changeset/stale-crabs-add.md
- packages/blade/src/components/Card/CardHeader.tsx
React Native's text reserves space for empty text here. Tried it with Native text instead of ours as well, same results.
(Notice the "Profile Information" alignment)
> fix: CardHeader title alignment when subtitle is not present

- .changeset/swift-dolphins-wink.md
- packages/blade/src/_helpers/types.ts
- packages/blade/src/components/BladeProvider/__tests__/paymentLightTheme/paymentLightTheme.web.ts
- packages/blade/src/components/BladeProvider/index.ts
- packages/blade/src/components/Box/BaseBox/useMemoizedStyles.web.ts
- packages/blade/src/components/Box/__tests__/useMemoizedStyles.web.test.tsx
- packages/blade/src/tokens/theme/bankingTheme.ts
- packages/blade/src/tokens/theme/paymentTheme.ts
- packages/blade/src/tokens/theme/theme.d.ts
> **Note**
>
> Will merge this PR separately after Layouts. Not that important right now and it can wait. You can review the PR though.
Working Sandbox: https://codesandbox.io/s/blade-theme-change-r736xm
Imagine a usecase where you want to watch when theme is changed. 
This is how you will currently do it.
```ts
const { theme } = useTheme();
React.useMemo(() => {/* something when theme is switched */}, [theme]);
```
This will likely not work as expected in most of the usecases because theme is a deep object.
The proposed solution is this -
```ts
const { theme } = useTheme();
React.useMemo(() => {/* something when theme is switched */}, [theme.name]);
```
So now you only watch when theme itself is switched from state. 
Also helpful for doing any conditional checks in the code like-
```ts …
```
> feat(theme): add name property to watch over theme changes

- .changeset/soft-melons-eat.md
- packages/blade/src/components/Checkbox/__tests__/__snapshots__/Checkbox.web.test.tsx.snap
- packages/blade/src/components/Link/BaseLink/BaseLink.tsx
- packages/blade/src/components/Link/BaseLink/__tests__/__snapshots__/BaseLink.native.test.tsx.snap
- packages/blade/src/components/Link/BaseLink/__tests__/__snapshots__/BaseLink.ssr.test.tsx.snap
- packages/blade/src/components/Link/BaseLink/__tests__/__snapshots__/BaseLink.web.test.tsx.snap
- packages/blade/src/components/Link/Link/__tests__/__snapshots__/Link.native.test.tsx.snap
- packages/blade/src/components/Link/Link/__tests__/__snapshots__/Link.ssr.test.tsx.snap
- packages/blade/src/components/Link/Link/__tests__/__snapshots__/Link.web.test.tsx.snap
- packages/blade/src/components/List/ListItem.tsx
- packages/blade/src/components/List/__tests__/__snapshots__/List.native.test.tsx.snap
React native has a vertical alignment bug that causes nested text which also has its own view inside to cause misalignment. This PR wraps all the children of list item (text and view) in a flex and aligns them. 
Ref: https://github.com/facebook/react-native/issues/31955
**Before this PR:**
**After this PR:**
> fix: ListItemLink alignment

- .changeset/nervous-eyes-lie.md
- packages/blade/package.json
Trying to see if this fixes bundlephobia for blade.
May or may not resolve #586. According to google search answers it should. Will need to test after creating npm release. I referred to this PR that came in google search https://github.com/nirtz89/crumbsjs/issues/5
Shouldn't break anything in existing setup because -
> If both exports and main are defined, the exports field takes precedence over main in supported versions of Node.js.
>
> ~ https://nodejs.org/api/packages.html#package-entry-points
> feat(package.json): add main field 

- .changeset/khaki-planets-shake.md
- packages/blade/src/hooks/useBladeInnerRef.ts
Fixes: #1013 #1090
`instanceof HTMLElement` tries to use HTMLElement as a value which is not available for react native. Added a platform check to ensure 
`instanceof HTMLElement` doesn't run.
> fix: ref breakage on react native

- .changeset/clever-kings-cover.md
- packages/blade/src/components/Link/BaseLink/BaseLink.tsx
- packages/blade/src/components/Link/BaseLink/__tests__/BaseLink.web.test.tsx
- packages/blade/src/components/Link/Link/Link.tsx
- packages/blade/src/components/Link/Link/__tests__/Link.web.test.tsx
Adds support for `title` attribute on web. Does nothing on native since there is no counterpart for showing a tooltip on links on native. We could add this as a feature later on where long pressing the link shows a Toast with the `title` but that would be when we build the Toast component. 
On hover:
> feat: add `htmlTitle` prop support for Link component on web

- .changeset/cool-students-study.md
- packages/blade/src/_helpers/types.ts
- packages/blade/src/components/Box/BaseBox/baseBoxStyles.ts
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/BaseBox/types/responsiveTypes.ts
- packages/blade/src/components/Box/styledProps/getStyledProps.ts
fixes #1112 and bunch of other types in Box and styled-props
- Created `PickCSSByPlatform` type utility which picks from `CSSObject` type in web and `ViewStyle` in react native and automatically returns `never` when prop doesn't exist on react native.
We won't have to explicitly handle types anymore.
> fix(Box): react-native style types

- .changeset/fifty-dryers-grin.md
- packages/blade/src/tokens/global/colors.ts
[Slack][1]
The value of `ashGrayLight.1200` is broken:
https://blade.razorpay.com/?path=/docs/tokens-colors--page#neutral-colors
[1]: https://razorpay.slack.com/archives/CMQ3RBHEU/p1681440228714499
> fix(colors): incorrect value of ashGrayLight.1200

- .changeset/honest-socks-sin.md
- packages/blade/src/components/Input/TextInput/TextInput.stories.tsx
- packages/blade/src/components/Input/TextInput/TextInput.tsx
- Adds new TextInput story
- Adds note on why we don't use `type="number"` internally
- Add jsdoc
There are several people who have asked this so far on slack - 
- https://razorpay.slack.com/archives/CMQ3RBHEU/p1681439709940449
- https://razorpay.slack.com/archives/C01H13RTF8V/p1678362249461709
and more so better to have a note in docs itself.
> feat(TextInput): add note on `type="number"` attribute

- .changeset/swift-dogs-teach.md
- packages/blade/src/components/Card/CardFooter.tsx
Resolves #1140 
When we do not provide either `footerTrailing` or `footerLeading` component to the `cardFooter` component, then it's always aligned to the right.
More information on this [issue](https://github.com/razorpay/blade/issues/1140)
Added a fix, so that the `footerTrailing` is alway aligned to the right.
> I did not provide the `footerLeading` component
> fix(cardFooter): alignment issue

- .changeset/plenty-cougars-smoke.md
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/components/BottomSheet/utils.ts
Changes: 
- Made the lower snapPoint dynamic based on the content of the height, to ensure we will always have some buffer between the lower snapPoint and the contentHeight. 
Explanation:
https://www.loom.com/share/a9a8db7688d64194b13df8b3e25859ae
> fix(blade): ensure that the BottomSheet's lower snappoint will have a buffer

- .changeset/nine-kids-march.md
- packages/blade/scripts/generateCssThemeVariables.js
Our shadow tokens changed to elevation tokens but we missed to update the CSS vars generating script. Since the script logged the error instead of throwing an error, we missed catching this on CI
> fix: css vars build script with new elevation tokens

- .changeset/dry-beers-greet.md
- packages/blade/package.json
Fixes the path to codemod. We will also need to release this fix to previous versions of blade.
> fix: update migrate-typography script

- .changeset/lazy-bottles-learn.md
- packages/blade/src/components/ActionList/ActionList.tsx
- packages/blade/src/components/BottomSheet/BottomSheet.native.tsx
Fixed react-native error "VirtualizedLists should never be nested inside plain ScrollViews"
ActionList's componentId accidentally got removed in this [commit](https://github.com/razorpay/blade/commit/fc8fef39b3eeac5d5f8ccec374a251d097475723#diff-56bfde9740ed80178b00a3439c5943a881552847e2caba74f7bc2d643962f899R159-R161), resulting in BottomSheet to not find the ActionList and satisfy this [condition](https://github.com/razorpay/blade/blob/36d8b2f563ae0ea33860d8bea214d207a3179d09/packages/blade/src/components/BottomSheet/BottomSheetBody.native.tsx#L21). 
> :( really need e2e tests to catch these issues
> fix(blade): BottomSheet unable to find ActionList component

- .github/actions/install-dependencies/action.yml
- .github/workflows/blade-chromatic.yml
- .github/workflows/blade-tokens-upload.yml
- .github/workflows/blade-validate.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
Fixes https://github.com/razorpay/blade/issues/1221
Install time reduced from 5mins to 25s 🔥 
[Example run](https://github.com/razorpay/blade/actions/runs/5261941118/jobs/9511043218?pr=1297).
> ci: setup cache for installing dependencies

- .changeset/fast-rings-count.md
- packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.web.test.tsx.snap
In `SelectInput` trigger, DropdownOverlay should not have minWidth and it should always take width of the input
Slack Issue: https://razorpay.slack.com/archives/CMQ3RBHEU/p1686718789586659
Resolves #1299
> fix(DropdownOverlay): DropdownOverlay width

- .changeset/few-llamas-doubt.md
- packages/blade/src/components/Amount/Amount.stories.tsx
- packages/blade/src/components/Amount/Amount.tsx
- packages/blade/src/components/Amount/__tests__/Amount.native.test.tsx
- packages/blade/src/components/Amount/__tests__/Amount.web.test.tsx
- packages/blade/src/components/Amount/__tests__/__snapshots__/Amount.native.test.tsx.snap
- packages/blade/src/components/Amount/__tests__/__snapshots__/Amount.web.test.tsx.snap
> fix: show decimal upto 2 places when `isAfixSubtle:false`

- packages/blade/package.json
- packages/blade/patches/react-native+0.66.5.patch
- yarn.lock
Followed @chaitanyadeorukhkar's suggestion after fixing some other errors and finally got the native builds working after this. This won't fix all the issues but it fixes a definite issue in an internal module.
Uses `patch-package` to patch the internal node module.
Run `yarn` after pulling this branch to let `patch-package` do its thing.
> fix(native): patch yoga.cpp react native internal

- .changeset/thick-bags-cry.md
- packages/blade/package.json
postinstall will be run even on consumers end when they install blade, so this will be needed as a direct dependency. Followup for #1309
> fix(patch-package): move to dependencies

- .github/workflows/blade-pr-title-check.yml
PR title check is failing on #1354 which comes from a forked repo. Trying to fix that as suggested at https://github.com/marocchino/sticky-pull-request-comment/issues/930#issuecomment-1515431005
> fix: PR title check workflow for forked repos

- packages/blade/src/utils/storybook/ComponentStatusTable.tsx
Have updated the component status page for divider component.
> docs(divider): updated component status

- .changeset/lovely-seals-rush.md
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/Box.stories.tsx
- packages/blade/src/components/Box/Box.tsx
- packages/blade/src/components/Box/__tests__/Box.native.test.tsx
- packages/blade/src/components/Box/__tests__/Box.ssr.test.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
- packages/blade/src/components/Typography/BaseText/types.ts
- packages/blade/src/components/Typography/Heading/Heading.stories.tsx
- packages/blade/src/components/Typography/Text/Text.stories.tsx
- packages/blade/src/components/Typography/Title/Title.stories.tsx
On Box, we're exposing all `brand.*` tokens on the background.
On Typography, we're exposing all `brand.primary.*` tokens as color prop
> feat(Box, Typography): expose brand colors

- .changeset/brown-frogs-call.md
- packages/blade/src/components/List/ListItemText.tsx
- packages/blade/src/components/List/index.ts
ListItemText is not exported right now for consumers https://razorpay.slack.com/archives/CMQ3RBHEU/p1689756239995169?thread_ts=1689159775.991879&cid=CMQ3RBHEU
> fix(List): re-export ListItemText

- packages/blade/src/components/Typography/Heading/Heading.stories.tsx
> docs: remove default size from story controls of heading

- packages/blade/src/components/Box/LayoutPrimitivesDocs.tsx
The Layout Primitives page is broken right now - https://blade.razorpay.com/?path=/docs/components-layout-primitives-box-layout-primitives-tutorial--page
the componentId was changed so I removed the static id and added MetaConstants variable now
> fix: Layout Primitive docs

- .changeset/nervous-chicken-explain.md
- packages/blade/src/components/Form/FormLabel.tsx
- packages/blade/src/components/Input/BaseInput/BaseInput.tsx
- packages/blade/src/components/Input/OTPInput/OTPInput.stories.tsx
- packages/blade/src/components/Input/OTPInput/OTPInput.tsx
- packages/blade/src/components/Input/PasswordInput/PasswordInput.stories.tsx
- packages/blade/src/components/Input/PasswordInput/PasswordInput.tsx
- packages/blade/src/components/Input/SelectInput/SelectInput.stories.tsx
- packages/blade/src/components/Input/SelectInput/SelectInput.tsx
- packages/blade/src/components/Input/TextArea/TextArea.stories.tsx
- packages/blade/src/components/Input/TextArea/TextArea.tsx
- packages/blade/src/components/Input/TextInput/TextInput.stories.tsx
- packages/blade/src/components/Input/TextInput/TextInput.tsx
Fixes https://github.com/razorpay/blade/issues/1237
I'm thrilled to introduce an important update to our TextInput component, aimed at improving accessibility and flexibility. With this latest release, we have made the `label` prop optional while introducing the all-new `accessibilityLabel` prop, ensuring an inclusive user experience for everyone.
**Optional `label` Prop**: We understand that not all use cases require a label for the TextInput. Therefore, we have made the label prop optional, providing you with the freedom to choose whether to display a label or not, depending on your specific application requirements.
**Introducing `accessibilityLabel`:** Recognizing the significance of accessibility in modern applications, we have added the `accessibilityLabel` prop to the TextInput. …
> feat(Input): make `label` prop optional & add `accessibilityLabel` prop

- packages/blade/docs/utils/useTheme.stories.mdx
- Heading, Text, Button are not available to import from utils.
- `useTheme` export from utils is not working as expected (#1497 )
> docs: update useTheme usage

- .changeset/thick-countries-search.md
- packages/blade/src/components/Box/BaseBox/types/propsTypes.ts
- packages/blade/src/components/Box/Box.tsx
- packages/blade/src/components/Box/__tests__/Box.native.test.tsx
- packages/blade/src/components/Box/__tests__/Box.ssr.test.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
https://github.com/razorpay/blade/assets/46647141/51595886-6c29-46f5-8d6e-38e215468ff3
> feat(Box): add support for `transparent` background color

- .github/workflows/blade-validate.yml
- Build blade step is not required to run tests and only adds up to the workflow time. We already have this step in the `Validate Source Code` job.
> ci: don't build blade for running tests

- packages/blade/package.json
RN typecheck was not running locally because we run `run-p types:typecheck:*` which was missing Native's script
> fix: native typecheck

- .changeset/flat-books-raise.md
- packages/blade/src/components/Card/Card.tsx
Fixes #1565 
Removed broken figma link
> chore(blade): remove broken figma link in `Card`

- packages/plugin-figma-blade-coverage/src/bladeLibraryConstants.ts
- packages/plugin-figma-blade-coverage/src/main.ts
This PR adds 3 enhancements to the Blade Coverage Figma Plugin
1. Detect and Flag overrides for a Blade Instance
2. Show Description in Highlighted nodes for self-assistance in understanding the flagged layers and fixing it
3. Traverse and calculate coverage for components where we have slots
> feat: add some capabilities to the Figma coverage plugin

- .changeset/wet-tips-admire.md
- packages/blade/src/components/Input/DropdownInputTriggers/index.ts
During AutoComplete I refactored types to be on different file. Missed exporting them from index.ts.
> fix: type exports for Select and AutoComplete

- .changeset/dry-llamas-explain.md
- packages/blade/src/components/Input/DropdownInputTriggers/AutoComplete.stories.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/AutoComplete.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/BaseDropdownInputTrigger.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/AutoComplete.native.test.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/AutoComplete.web.test.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/__snapshots__/AutoComplete.web.test.tsx.snap
- packages/blade/src/components/Input/DropdownInputTriggers/types.ts
AutoComplete when used in single selection controlled version, was not changing its input value on selection change.
In AutoComplete single select, the value displayed inside AutoComplete is inputValue. When we select item in controlled version, we also have to set its inputValue to the selection
> fix(AutoComplete): controlled single selection

- .changeset/yellow-melons-deliver.md
- packages/blade/src/components/Dropdown/dropdownUtils.ts
- packages/blade/src/components/Input/DropdownInputTriggers/AutoComplete.tsx
In certain cases where data needs to be fetched and rendered in item, we have to re-calculate the first item and set focus ring on it on change of options. This PR does that.
> fix(AutoComplete): handle focus ring on option change

- .changeset/forty-garlics-turn.md
- packages/blade/src/components/BottomSheet/BottomSheet.stories.tsx
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.web.test.tsx
- packages/blade/src/components/BottomSheet/__tests__/__snapshots__/BottomSheet.web.test.tsx.snap
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/__snapshots__/AutoComplete.web.test.tsx.snap
Fixes #1686 
In this PR: 
- Removed FloatingFocusManager and reverted back to manual focus management
- Added tests
- Fixed tests to use getByRole
Reference PR: https://github.com/razorpay/blade/pull/1489
--- 
Context: https://razorpay.slack.com/archives/CMQ3RBHEU/p1695972277506429?thread_ts=1693739607.070049&cid=CMQ3RBHEU
> In [this](https://github.com/razorpay/blade/pull/1489) PR we added the "[FloatingFocusManager](https://floating-ui.com/docs/floatingfocusmanager)" from FloatingUI to automate the focus management logic and added the modal=true prop to it, this [modal](https://floating-ui.com/docs/floatingfocusmanager#modal) prop will ensure that everything outside of the FloatingFocusManager will get aria-hidden which simulates the [inert](https://github.com/WICG/inert) prop so that …
> fix: remove FloatingFocusManager and added more tests

- .changeset/bright-pumpkins-push.md
- packages/blade/src/components/List/ListItemText.tsx
- packages/blade/src/components/List/__tests__/__snapshots__/List.web.test.tsx.snap
Issue: https://github.com/razorpay/blade/issues/1696
Context: `Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>`
`<ListItemText />` uses `<p>` tag by default and `<ListItem />` renders a `<p>` tag as well which is causing the aforementioned issue.
Solution: ListItemText uses Text component which renders `<p>` tag by default. However, for almost all the use-cases ListItemText will get rendered inside ListItem and we can make `<span>` as default
https://razorpay.slack.com/archives/CMQ3RBHEU/p1696501813630969
> feat(ListItemText): making span as default tag for ListItemText

- packages/blade/src/components/Tooltip/Tooltip.web.tsx
- packages/blade/src/components/Tooltip/__tests__/Tooltip.web.test.tsx
- packages/blade/src/components/Tooltip/__tests__/__snapshots__/Tooltip.web.test.tsx.snap
Fixes https://github.com/razorpay/blade/issues/1386
The issue exists on the web only because we don't set the `accessibilityLabel` prop to trigger on react-native.
https://github.com/razorpay/blade/blob/7c116d54164124651fe420a93f182fb4caf49cf9/packages/blade/src/components/Tooltip/Tooltip.native.tsx#L72-L80
> fix(Tooltip): prevent overriding the `aria-label` attribute

- packages/blade/docs/guides/Installation.stories.mdx
Two of these links were broken and showed a **404 error**. I have updated them to redirect to the intended page. 
Also, I have made a few **grammatical corrections** in the guide. Thanks :)
> docs: Fixed links that were broken in Installation.stories.mdx

- .changeset/tricky-mice-tie.md
- packages/blade/src/components/ActionList/ActionListItem.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/__snapshots__/AutoComplete.native.test.tsx.snap
Fixes #1733 
There was some additional spacing around Checkbox earlier which we removed in #1661 but that changed spacing for Checkbox in ActionListItem as well.
This PR adds some new spacing around checkbox of ActionListItem to fix it.
Before this PR
After this PR
> fix(ActionListItem): checkbox spacing

- packages/examples/basic/package.json
Nonexact versions of react & react-dom were leading to dedupe not working as expected. This resolves it and ensures react and react-dom is deduped from the final bundle of the example.
> chore: fix dedupe issue on the basic example

- .changeset/plenty-ligers-study.md
- packages/blade/src/components/Form/Selector/SelectorLabel.web.tsx
Fixes: #1746
Removed preventDefault from SelectorLabel onMouseDown event which was causing Radio to behave oddly while any text is selected. 
The preventDefault was previously added because when using a mouse and toggling a component like checkbox there was a focus flicker which was happening and we wanted to prevent that: 
**with preventDefault:** 
https://github.com/razorpay/blade/assets/35374649/01770544-b81b-496b-be55-e4fdfbc1e4d3
**without preventDefault:**
https://github.com/razorpay/blade/assets/35374649/d00d6532-62df-4ee8-96b5-91efe1f6d002
But after the `focus-visible` change in #1670 that we made this is no longer needed since focus won't be visible when clicking with mouse, so removed it.
> fix(blade): remove preventDefault in selector label

- packages/blade/src/components/Dropdown/_decisions/decisions.md
- rfcs/2023-01-06-layout.md
Resolves #1172 
Moved information from our [Layout Discussion Doc](https://docs.google.com/document/d/1Ifcgh1hXvEykO8YbfcyiWoFktAHSe57xXiPz53Puew8/edit#heading=h.wcduvwj40y7e) and [Dropdown Triggers API Doc](https://docs.google.com/document/d/1vxwF_CuF6dDYJuIcxck16jusfufWhMJflWbeQG9SD3o/edit#heading=h.ajyy8ugby849) to their respective API decisions
> docs: Move Google Docs info to API Decisions

- packages/blade/docs/guides/Installation.stories.mdx
Notifies blade users about the `styled-components` version (v5) supported by blade
> chore(installation): add note for styled-components supported version

- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
pnpm is broken from stackblitz-side for some reason.
Also yarn's clean install is faster than pnpm and npm so might increase dependency installation speed a bit.
> fix(StackblitzEditor): use yarn instead of pnpm in examples

- rfcs/2023-11-08-font-loading-strategy.md
Since we're using 3 weights on inter now. The static font size becomes almost same as variable font. I think its better to load variable font in this scenario since it will give us more control and size difference is not that big.
> feat(rfc-font-loading-strategy): conclude to using variable fonts in both

- packages/examples/basic/package.json
- packages/examples/basic/src/index.tsx
- packages/examples/basic/yarn.lock
- yarn.lock
Earlier we were pointing to `blade/build` instead of `blade` the package so we could just pick the things from root imports like `blade/components`. But in this setup it was trying to pick React from `node_modules/@razorpay/blade/node_modules` and not the root node_modules
**New Approach**
- Use `../../blade` instead of `../../blade/build` so we don't install build directory but blade package which includes package.json exports so it respects our original exports directories and doesn't rely on paths
- We then remove the node_modules from blade directory in the `postinstall` of example so example doesn't look inside blade's node_modules for React and picks it from root of example
> fix: local basic build

- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/AutoComplete.web.test.tsx
Skipping the flaky AutoComplete test. It is getting timed out on CI after 5 second but executes in 1 second locally. Not sure why 🤦🏼
> fix: skip the flaky autocomplete test

- .changeset/pretty-clocks-end.md
- packages/blade/src/components/Form/FormLabel.tsx
- packages/blade/src/components/Typography/BaseText/BaseText.web.tsx
- packages/blade/src/components/Typography/BaseText/getBaseTextStyles.ts
- packages/blade/src/components/Typography/BaseText/types.ts
- packages/blade/src/components/Typography/Text/Text.tsx
image Previously, single words exceeding a specified width of 120px were truncated, potentially impacting readability and aesthetics. Added new prop for wordBreak in BaseText and also expose it in the Text component.
> fix: refined text input label truncation for single-word overflow

- .changeset/fluffy-chicken-hunt.md
- packages/blade/.storybook/react/global.css
- packages/blade/.storybook/react/preview.js
- packages/blade/package.json
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/utils/useScrollLock.ts
- yarn.lock
Fixes #1860 
There's a bug in the body-scroll-lock packages which causes iOS mobile to scroll to the top when bottomsheet opens. 
https://github.com/willmcpo/body-scroll-lock/issues/237
I've updated the lib with the community fixed version. 
And also updated the storybook canvas to NOT use absolute positioning while rendering the stories which causes issues because this is not how most consumers use our components.
> fix(blade): page gets scrolled to top on iOS on bottomsheet open

- .changeset/pretty-wolves-deny.md
- packages/blade/.storybook/react-native/storybook.requires.js
- packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx
- packages/blade/src/components/Dropdown/StyledDropdownOverlay.tsx
- packages/blade/src/components/Dropdown/docs/DropdownWithButton.stories.tsx
- packages/blade/src/components/Dropdown/types.ts
This PR is in reference to adding width support to DropdownOverlay. Now users can choose to have the width of the dropdown or it will be set to "100%"
Fixes #1660
> feat(Dropdown): support `width` prop on DropdownOverlay

- packages/blade/docs/guides/Installation.stories.mdx
I used the Tabs component in react-native but received the error mentioned below when I built the app. It resolved once I added the `react-native-pager-view` dependency to my project. Hence, I've updated the Blade's documentation for the same.
Although I'm confused why it only showed error for `react-native-pager-view` & not `react-native-tab-view`. From what I know, that is also a required package as it's mentioned in [blade's package.json](https://github.com/razorpay/blade/blob/af070d3758739576ec454d6a40d68ed997e78b3d/packages/blade/package.json#L126).
<details><summary>Error</summary>
<p>
```
ERROR  Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.
This error is located at:
in RNCViewPager (created by PagerView)
in PagerView
in Unknown (created …
```
> docs: add react-native-pager-view in RN install guide

- packages/blade/.storybook/react/main.js
- packages/blade/docs/guides/Installation.stories.mdx
- packages/blade/ios/blade.xcodeproj/project.pbxproj
- packages/blade/ios/blade/Info.plist
- packages/blade/ios/link-assets-manifest.json
I updated the font file names somewhere so it required running `npx react-native-asset -ios-a` once to update the instances where the older font file name was used. 
This PR fixes that.
It also adds back the documentation of new font installation which somewhere got reverted while pulling master on rebranding/master
> fix: React Native iOS fonts

- packages/blade/.storybook/react/main.js
- packages/blade/src/components/Indicator/Indicator.stories.tsx
- packages/blade/src/components/Indicator/Indicator.tsx
- packages/blade/src/components/Typography/Code/Code.tsx
- Rename `intent` to `color`
- Fix Code component color and add typography to migrated documentation
> fix: Indicator intent prop, Code component color

- packages/blade/src/components/Tooltip/TooltipContent.tsx
- packages/blade/src/components/Tooltip/__tests__/__snapshots__/Tooltip.web.test.tsx.snap
Regarding issue: #1842 
Previous behaviour: tooltip content text was overflowing
After fix:
> fix: Tooltip component - Content is not getting wrapped inside tooltip

- packages/blade/src/components/ProgressBar/ProgressBar.tsx
- packages/blade/src/components/Typography/BaseText/types.ts
- packages/blade/src/components/Typography/Text/Text.tsx
Removed FormLabel from ProgressBar since it's not using the base form label in design. 
https://razorpay.slack.com/archives/G01B3LQ9H0W/p1703663341935119
> refactor(rebranding): fix progressbar label text style

- packages/blade/src/components/Form/FormLabel.tsx
- packages/blade/src/components/Typography/Text/Text.tsx
- packages/blade/src/components/Typography/Text/__tests__/Text.native.test.tsx
- packages/blade/src/components/Typography/Text/__tests__/Text.web.test.tsx
Rename caption size `medium` to `small`
PR for codemod: #1926 
```diff
- <Text variant="caption" size="medium">This is a help text</Text>
+ <Text variant="caption" size="small">This is a help text</Text>
```
> chore: change text caption size to `small` instead of `medium`

- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-colors.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-typography.test.ts
- packages/blade/codemods/brand-refresh/transformers/index.ts
- packages/blade/jest.web.config.js
- packages/blade/upgrade-v11.md
- **The `caption` variant of the `Text` component now accepts only `size="small"`.**
```diff
- <Text variant="caption" size="medium"> Hello </Text>
+ <Text variant="caption" size="small"> Hello </Text>
```
> feat: add codemod for Text component migration

- .changeset/famous-cats-push.md
- packages/blade/src/components/Table/TablePagination.web.tsx
- packages/blade/src/components/Table/__tests__/Table.web.test.tsx
Fixes #1925 
- Fix an edge case where the controlled prop `currentPage` being greater that the total pages makes the table go in an infinite state update. 
- Throw appropriate error
- Add test
> fix(Table): handle case where currentPage is greater than total pages

- CODEOWNERS
Reduce review noise on slack & keep minimal codeowners.
> chore: keep minimal codeowners to reduce noise

- package.json
> chore: remove razorsharp from workspace packages

- .changeset/quick-students-beam.md
- packages/blade/src/components/Table/TableBody.web.tsx
- packages/blade/src/components/Table/__tests__/Table.web.test.tsx
- packages/blade/src/components/Table/__tests__/__snapshots__/Table.web.test.tsx.snap
- packages/blade/src/components/Table/types.ts
Makes rows hoverable without them needing to be selectable. Consumers can decide what they want to do on hover.
Ref: [Issue raised on slack](https://razorpay.slack.com/archives/CMQ3RBHEU/p1704712316037749)
Resolves: #1966
> chore: add `onHover` & `onClick` callback to `TableRow`

- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-actionlist.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-amount.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-badge.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-card.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-colors.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-contrast-intent-variant.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-divider.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-dropdown.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-typography.test.ts
- packages/blade/codemods/brand-refresh/transformers/index.ts
- packages/blade/codemods/brand-refresh/transformers/migrate-actionlist.ts
- packages/blade/codemods/brand-refresh/transformers/migrate-amount.ts
- packages/blade/codemods/brand-refresh/transformers/migrate-badge.ts
- packages/blade/codemods/brand-refresh/transformers/migrate-contrast-intent-color-props.ts
- packages/blade/codemods/brand-refresh/transformers/migrate-dropdown.ts
- packages/blade/codemods/brand-refresh/transformers/migrate-typography.ts
- packages/blade/upgrade-v11.md
- [JIRA Story](https://razorpay.atlassian.net/browse/FC-2575?atlOrigin=eyJpIjoiMmNjZjY2ODU1ZTYzNDBiNzg4OTc4OTIwYWJhNWZjODIiLCJwIjoiaiJ9)
> feat: add codemod for Alert, Skeleton, Card, Chip, & Dropdown

- .changeset/tiny-cooks-relate.md
- packages/blade/src/components/Dropdown/Dropdown.tsx
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.ssr.test.tsx.snap
- packages/blade/src/components/Dropdown/__tests__/__snapshots__/Dropdown.web.test.tsx.snap
- packages/blade/src/components/Dropdown/docs/DropdownWithButton.stories.tsx
- packages/blade/src/components/Input/BaseInput/BaseInputTagSlot.web.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/__snapshots__/AutoComplete.ssr.test.tsx.snap
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/__snapshots__/AutoComplete.web.test.tsx.snap
Fixes 2 issues -
1. Hides scrollbar from tag slot ([reference - Internal Slack](https://razorpay.slack.com/archives/CMQ3RBHEU/p1707983918459799?thread_ts=1707983890.941129&cid=CMQ3RBHEU))
2. Click on DropdownLink and DropdownButton icon was not working which is fixed ([referrence](https://twitter.com/championswimmer/status/1758053933799690424?s=46&t=z3Gl4H0P-0tu0p7yvK1HbQ))
- The clicks on icon of DropdownLink and DropdownButton were not working because when we click these icons, we trigger `setIsOpen(true)` and switch the icon from chevron down to chevron up. The icon that is clicked now no longer exists because of switch in icons in React DOM and DOM so our `dropdown.contains(target)` check (which checks if outside item is clicked was getting false)
- This is fixed by adding …
> fix(Dropdown): remove scrollbar on tag slot and clicks on icon

- .changeset/three-humans-divide.md
- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
As `@razorpay/i18nify-js` dependency was not added in sandbox environment, the sandbox was breaking with the error "Could not find @razorpay/i18nify-js dependency". 
Have added a fix for this issue in this PR.
Slack thread => 
https://razorpay.slack.com/archives/C01H13RTF8V/p1707796443539579 
Issue =>
Fix =>
> fix: i18nify-js local dependency added in sandboxes

- .changeset/beige-scissors-warn.md
- packages/blade/src/components/Dropdown/docs/DropdownWithSelect.stories.tsx
- packages/blade/src/components/Tag/AnimatedTag.web.tsx
- packages/blade/src/components/Tag/Tag.tsx
- packages/blade/src/components/Tag/__tests__/__snapshots__/Tag.native.test.tsx.snap
- packages/blade/src/components/Tag/__tests__/__snapshots__/Tag.ssr.test.tsx.snap
- packages/blade/src/components/Tag/__tests__/__snapshots__/Tag.web.test.tsx.snap
Tag component was shrinking when placed inside flex of AutoComplete and SelectInput
- Adds `flexShrink={0}` to disable shrinking behaviour and take comfortable space
> fix(Tag): tag truncation in Select and AutoComplete

- packages/blade/src/components/Breadcrumb/_KitchenSink.Breadcrumb.stories.tsx
- packages/blade/src/components/Breadcrumb/__tests__/Breadcrumb.ssr.test.tsx
- packages/blade/src/components/Breadcrumb/__tests__/Breadcrumb.web.test.tsx
- packages/blade/src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.ssr.test.tsx.snap
- packages/blade/src/components/Breadcrumb/__tests__/__snapshots__/Breadcrumb.web.test.tsx.snap
> test: add breadcrumb tests

- .changeset/rare-kiwis-rush.md
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-colors.test.ts
- packages/blade/codemods/brand-refresh/transformers/__tests__/migrate-typography.test.ts
- packages/blade/codemods/brand-refresh/transformers/index.ts
- packages/blade/codemods/brand-refresh/transformers/migrate-typography.ts
Handles few more cases for dashboard migration
- Handle `brand.primary[500]` token syntax migration.
- Add Text import when changing `Heading -> Text`
> fix: cover more cases with codemod

- .changeset/hot-dodos-sin.md
- packages/blade/src/components/Dropdown/DropdownOverlay.web.tsx
- packages/blade/src/components/Dropdown/types.ts
Allow manual placement of the dropdown.
- Add `placement` prop.
Needed for ButtonGroup component.
> feat: support `defaultPlacement` prop on `DropdownOverlay`

- packages/blade/src/components/ButtonGroup/StyledButtonGroup.tsx
- packages/blade/src/components/ButtonGroup/__tests__/ButtonGroup.ssr.test.tsx
- packages/blade/src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.ssr.test.tsx.snap
- packages/blade/src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.web.test.tsx.snap
Fixed the focus ring styles.
https://github.com/razorpay/blade/assets/46647141/7bdec257-fdaa-4668-9ffb-7dc58dfba257
> fix: ButtonGroup focus ring styles

- packages/blade/src/components/Table/TableBody.web.tsx
For a Multiselect Table Component, selection does not work if we click on the checkbox. However, it works if we click on the row itself. This PR is a short term solution to fix the problem.
Provided the issue link below for more details.
Stop event propagation while clicking on the multiselect checkbox
https://github.com/razorpay/blade/issues/1978
> fix(Table): selection toggle for multiselect table

- .changeset/tiny-beds-switch.md
- packages/blade/src/components/Amount/Amount.tsx
Fixes #2115 
Passing below extra paramters to i18nify library to retain fraction digits in compact formatted value. 
```
minimumFractionDigits: 1,
trailingZeroDisplay: 'stripIfInteger',
```
For more detail on these attributes, refer to the [Intl API documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat).
> fix: additional parameters added to retain fraction digits in humanize Amount figure

- .changeset/heavy-doors-impress.md
- packages/blade/src/components/Input/PhoneNumberInput/CountrySelector.web.tsx
fixes #2136
With the #2119 PR we added an [onClick handler](https://github.com/razorpay/blade/pull/2119/files?file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&show-viewed-files=true#diff-ef9c43555213ed0ff62057f117703311509720acc1d187a6155e2e2f0c9f4d74R949-R953) to the BaseInputWrapper to be able to focus the input whenever user clicks on the Input wrapper. 
This caused the PhoneInput dropdown to fail like so: 
1. User clicks the PhoneInput
2. The Dropdown **actually** opens
3. But since the BaseInputWrapper also got clicked, the input got focused
4. Because input got focused the dropdown automatically closed (since dropdowns get closed once blurred)
> fix(blade): phone number input dropdown not opening

- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
The container had display="flex" so it was stretching our components to full width by default. Fixed it along with some minor UI fixes for borders of logger.
> fix(StackblitzEditor): container alignment and minor ui fixes

- .eslintrc.js
Eslint timing analysis before optimizations: 
Rule                                        | Time (ms) | Relative
:-------------------------------------------|----------:|--------:
import/no-cycle                             | 30863.247 |    49.3%
prettier/prettier                           | 10177.949 |    16.3%
import/no-deprecated                        |  6499.778 |    10.4%
@typescript-eslint/no-unused-vars           |  3014.236 |     4.8%
@typescript-eslint/no-floating-promises     |  1632.403 |     2.6%
@typescript-eslint/no-unnecessary-qualifier |  1472.390 |     2.4%
@typescript-eslint/no-misused-promises      |   932.970 |     1.5%
import/order                                |   644.840 |     1.0%
import/no-extraneous-dependencies           |   494.785 |     0.8% …
> chore: improve eslint performance

- packages/blade/src/components/Avatar/_decisions/decisions.md
> docs: Avatar component API

- .changeset/eight-mirrors-tap.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
> Uploading a file, deleting it and then re-uploading the same file again is not working for some reason. Can you please check.
[Reported on Slack](https://razorpay.slack.com/archives/C01H13RTF8V/p1716802715000079?thread_ts=1716802466.589119&cid=C01H13RTF8V)
https://github.com/razorpay/blade/assets/46647141/3d65a183-c83e-49d6-b514-37c05b6c9dc0
https://stackoverflow.com/questions/4109276/how-to-detect-input-type-file-change-for-the-same-file
> fix(FileUpload): allow re-uploading the same file

- .changeset/eight-elephants-grin.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
- packages/blade/src/components/FileUpload/FileUploadItem.tsx
- packages/blade/src/components/FileUpload/StyledFileUploadItemWrapper.tsx
- packages/blade/src/components/FileUpload/types.ts
- [Slack thread](https://razorpay.slack.com/archives/CMQ3RBHEU/p1715935302377269?thread_ts=1715935039.903429&cid=CMQ3RBHEU)
- Added `onReupload` prop, to be used in case of error state.
https://github.com/razorpay/blade/assets/46647141/84f911c1-ae77-4c71-bf38-9a2a840cf1e3
> feat(FileUpload): add `onReupload` prop in case of error state

- .changeset/fifty-cougars-fry.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
- packages/blade/src/components/FileUpload/__tests__/__snapshots__/FileUpload.web.test.tsx.snap
- [Reported on slack.](https://razorpay.slack.com/archives/C01H13RTF8V/p1719212583215179?thread_ts=1719209184.597759&cid=C01H13RTF8V).
- Please check [this](https://stackblitz.com/edit/kr8qdz?file=App.tsx) link for repro.
https://github.com/razorpay/blade/assets/46647141/2643a592-15d9-41a0-83c3-4f515d1ac8c7
> fix(FileUpload): correctly udpate state in controlled mode

- .changeset/olive-spies-provide.md
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.native.test.tsx.snap
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.web.test.tsx.snap
- packages/blade/src/tokens/theme/createTheme.ts
> fix: white-labeling issue with surface text primary

- .changeset/popular-paws-explain.md
- packages/blade/src/components/Table/Table.web.tsx
- packages/blade/src/components/Table/types.ts
Enables rows to be clickable as a whole or only on the checkbox.
Fixes: https://github.com/razorpay/blade/issues/2273
> feat: add multiselection-mode prop 

- packages/blade/src/components/Table/Table.web.tsx
- packages/blade/src/components/Table/__tests__/Table.web.test.tsx
- packages/blade/src/components/Table/docs/BasicTable.stories.tsx
- packages/blade/src/components/Table/docs/stories.ts
- packages/blade/src/components/Table/types.ts
Fixes: https://github.com/razorpay/blade/issues/2271
> fix: table multiselect with pagination bug

- .changeset/violet-donuts-cross.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
- packages/blade/src/components/FileUpload/docs/FileUpload.stories.tsx
> fix: change onRemove/onReupload params

- packages/plugin-figma-blade-coverage/.npmrc
- packages/plugin-figma-blade-coverage/README.md
- packages/plugin-figma-blade-coverage/src/bladeLibraryConstants.ts
- packages/plugin-figma-blade-coverage/src/main.ts
- packages/plugin-figma-blade-coverage/yarn.lock
Added/Updated following components - 
- Accordion 
- Drawer
- Menu 
- Step Group 
- Top Nav
- FileUpload
- ButtonGroup
> feat: update coverage plugin with latest components

- .changeset/funny-toes-attack.md
- packages/blade/src/components/Link/Link/Link.stories.tsx
- packages/blade/src/components/Link/Link/Link.tsx
> feat: expose link negative/positive colors

- .changeset/cyan-drinks-poke.md
- packages/blade/src/components/Table/Table.web.tsx
- packages/blade/src/components/Table/__tests__/__snapshots__/Table.web.test.tsx.snap
- packages/blade/src/components/Table/tokens.ts
Fixes #2215 
Adds z-index to sticky column
> fix(Table): table sticky column z-index

- .changeset/swift-cougars-attend.md
- packages/blade/src/components/ActionList/ActionList.stories.tsx
- packages/blade/src/components/ActionList/ActionListItem.tsx
- packages/blade/src/components/ActionList/actionListUtils.ts
- packages/blade/src/components/ActionList/componentIds.ts
Support for Avatar in ActionListItem leading
> feat(ActionList): add ActionListItemAvatar component for leading prop

- .changeset/poor-geese-hug.md
- packages/blade/src/components/BottomSheet/__tests__/BottomSheet.web.test.tsx
- packages/blade/src/components/Input/DropdownInputTriggers/__tests__/AutoComplete.web.test.tsx
- packages/blade/src/components/Table/Table.web.tsx
- packages/blade/src/components/Table/TableBody.web.tsx
- packages/blade/src/components/Table/__tests__/Table.web.test.tsx
- packages/blade/src/components/Table/__tests__/__snapshots__/Table.web.test.tsx.snap
- packages/blade/src/components/Table/docs/BasicTable.stories.tsx
- packages/blade/src/components/Table/types.ts
- Add `defaultSelectedIds` to Table component
- Fixes https://razorpay.atlassian.net/browse/DSSUP-90
> feat(Table): add `defaultSelectedIds` prop

- packages/blade/docs/guides/Installation.stories.mdx
Accordion says "follow steps below" and we expect people to click on it to expand but there are other setup steps after the accordion which may lead to confusion and people not expanding the accordion
> chore: keep the prerequisite accordion open

- .changeset/yellow-avocados-brake.md
- packages/blade/src/components/Table/TableBody.web.tsx
- packages/blade/src/components/Table/TableEditableCell.web.tsx
- packages/blade/src/components/Table/__tests__/__snapshots__/Table.web.test.tsx.snap
Fixes #2222 
Code: 
```jsx
<TableCell>E03CXQ6CAQ6/C074E2N774G</TableCell>
```
Result: 
-----
Code:
```jsx
<TableCell>
<Text truncateAfterLines={1}>E03CXQ6CAQ6/C074E2N774G</Text>
</TableCell>
```
Result:
> fix(blade): Table cell text truncation

- packages/blade/docs/guides/Intro.stories.mdx
Fixes [#2380]
When we view the intro page https://blade.razorpay.com/?path=/docs/guides-intro--docs, the screen looks odd.
After fix
> fix: Mobile View in Intro Page of https://blade.razorpay.com/?path=/docs/guides-intro--docs

- packages/blade/docs/guides/Intro.stories.mdx
Fixes [#2381]
The url for Check the current [availability status of rebranded components here](http://localhost:9009/?path=/docs/guides-component-status--docs) points to localhost instead of https://blade.razorpay.com/?path=/docs/guides-component-status--docs.
Have updated the url.
> fix: Fixed url in https://blade.razorpay.com/

- .changeset/late-eels-live.md
- packages/blade/src/components/Input/BaseInput/BaseInput.tsx
Fix for `maxCharacters` alignment in Input component
When `maxCharacters` and `successText` props are passed to the component, but `validationState` prop is set to `none`, then `maxCharacters` indication is aligned to the left.
Made changes to `willRenderHintText` boolean condition to return true on the below scenarios:
- when `helpText` prop is passed
- when `successText` prop is passed and `validationState` prop is set to `success`
- when `errorText` prop is passed and `validationState` prop is set to `error`
> fix: maxCharacters alignment in Input field

- .changeset/smart-pots-complain.md
- packages/blade/package.json
- packages/blade/src/utils/storybook/Sandbox/StackblitzEditor/Sandbox.web.tsx
- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
- yarn.lock
For some reason stackblitz is trying to find package in react 19 even though we have react 18 marked in dependencies 🤦🏼 . Just updating to react 19 in examples for now. There aren't any major breaking changes apart from deprecated APIs being removed
> fix(stackblitz): move examples to react 19

- packages/blade/docs/guides/Installation.stories.mdx
- packages/blade/docs/migration-docs/upgrade-v12.md
- packages/blade/package.json
- packages/blade/rollup.config.mjs
- packages/blade/src/components/BaseMotion/docs/MotionInstallation.mdx
- packages/blade/src/utils/storybook/Sandbox/baseCode.ts
So due the name change of framer-motion -> motion. There's several gotchas that we end up with on consumer depending on bundlers and package installers they are using. E.g.
- pnpm fails when you install subdependency because it has flat directory structure so there we have to provide extra custom config that resolves the correct package. But it works fine in yarn and npm
- vite is resolving motion and framer-motion as separate instances for some reasons so provider of motion + animation from framer-motion is not working correctly
- I tried to mark motion as external package in build but that too starts throwing other babel issues
There are configs and ways to solve these for each bundler and package installer but that makes our upgrade guide confusing and things can break with those hacky …
> fix: recommend `framer-motion` name installation instead of `motion/react`

- .changeset/young-dragons-poke.md
- packages/blade/src/components/Button/IconButton/IconButton.tsx
- packages/blade/src/components/Button/IconButton/StyledIconButton.web.tsx
- packages/blade/src/components/Button/IconButton/types.ts
- packages/blade/src/components/ButtonGroup/ButtonGroup.web.tsx
- packages/blade/src/components/ButtonGroup/__tests__/ButtonGroup.web.test.tsx
- packages/blade/src/components/ButtonGroup/docs/ButtonGroup.stories.tsx
- packages/blade/src/components/ButtonGroup/types.ts
- packages/blade/src/components/Drawer/Drawer.web.tsx
- packages/blade/src/components/Radio/Radio.tsx
- packages/blade/src/components/Radio/RadioGroup/RadioGroup.tsx
- packages/blade/src/components/Radio/RadioGroup/useRadioGroup.ts
- packages/blade/src/components/Radio/useRadio.ts
- packages/blade/src/components/SideNav/SideNavItems/SideNavLink.web.tsx
- packages/blade/src/components/SideNav/docs/SideNav.stories.tsx
- packages/blade/src/components/SideNav/types.ts
- packages/blade/src/components/Tooltip/Tooltip.web.tsx
- packages/blade/src/components/Tooltip/componentIds.ts
- packages/blade/src/utils/useControllable.ts
- packages/blade/src/utils/useControllable.web.test.tsx
Drawer: 
- Changed the drawer's showOverlay behaviour to not mandate the overlay on level2 stacking
- Exposed ref
RadioGroup:
- Exposed event in onChange
ButtonGroup:
- Added styled props
- Added support for Tooltip inside ButtonGroup
IconButton:
- Added styledProps
SideNavLink:
- Added onClick
> feat(blade): Changes in components for X migration

- packages/blade/src/utils/storybook/componentStatusData.ts
> feat: component status table update

- .changeset/chatty-dolphins-care.md
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
> fix: cleanup bodyscroll locks if bottomsheet is force unmounted

- packages/blade/src/components/SideNav/SideNav.web.tsx
- packages/blade/src/utils/storybook/componentStatusData.ts
Fixes empty spacing when the component rendered inside banner returns null
https://razorpay.atlassian.net/browse/DSSUP-180
> fix(SideNav): empty padding in banner

- .changeset/tidy-lies-confess.md
- packages/blade/package.json
- packages/blade/src/components/ActionList/ActionList.tsx
- packages/blade/src/components/ActionList/ActionListBox.native.tsx
- packages/blade/src/components/ActionList/ActionListBox.web.tsx
- packages/blade/src/components/ActionList/ActionListItem.tsx
- packages/blade/src/components/ActionList/docs/propsTable.tsx
- packages/blade/src/components/ActionList/styles/getBaseListBoxWrapperStyles.ts
- packages/blade/src/components/BaseMenu/BaseMenuItem/BaseMenuItem.tsx
- packages/blade/src/components/BaseMenu/BaseMenuItem/StyledMenuItemContainer.web.tsx
- packages/blade/src/components/BaseMenu/BaseMenuItem/getBaseMenuItemStyles.ts
- packages/blade/src/components/BaseMenu/BaseMenuItem/tokens.ts
- packages/blade/src/components/Dropdown/docs/DropdownWithSelect.stories.tsx
- yarn.lock
Adds `isVirtualized` prop to ActionList to virtualize the items
Example: https://codesandbox.io/p/sandbox/trusting-feather-wphnnc?workspaceId=ws_CscdT6KxPm5VEoVzhtZAMq
> feat(ActionList): add Virtualization

- .changeset/tidy-lies-confess.md
- packages/blade/package.json
- packages/blade/src/components/ActionList/ActionList.tsx
- packages/blade/src/components/ActionList/ActionListBox.native.tsx
- packages/blade/src/components/ActionList/ActionListBox.web.tsx
- packages/blade/src/components/ActionList/ActionListItem.tsx
- packages/blade/src/components/ActionList/docs/propsTable.tsx
- packages/blade/src/components/ActionList/styles/getBaseListBoxWrapperStyles.ts
- packages/blade/src/components/BaseMenu/BaseMenuItem/BaseMenuItem.tsx
- packages/blade/src/components/BaseMenu/BaseMenuItem/StyledMenuItemContainer.web.tsx
- packages/blade/src/components/BaseMenu/BaseMenuItem/getBaseMenuItemStyles.ts
- packages/blade/src/components/BaseMenu/BaseMenuItem/tokens.ts
- packages/blade/src/components/Dropdown/docs/DropdownWithSelect.stories.tsx
- yarn.lock
> feat(ActionList): add Virtulization (v11)

- .changeset/yellow-cameras-knock.md
- packages/blade/src/components/DatePicker/Calendar.web.tsx
- packages/blade/src/components/DatePicker/CalendarHeader.web.tsx
- packages/blade/src/components/DatePicker/DateInput.web.tsx
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
- packages/blade/src/components/DatePicker/types.ts
- Added dateFormat and placeholder props:
The dateFormat prop allows custom formatting for the date displayed in the input.
The placeholder prop enables customization of the placeholder text, which defaults to the date format. This is useful since the placeholder text might differ from the date format or could be unclear to users.
- Removed the chevron icon when the picker prop is used.
this fixes - 
https://github.com/razorpay/blade/issues/2469 
https://github.com/razorpay/blade/issues/2470
> feat: add dateformat and placeholder prop for datepicker input [DSSUP-199]

- .changeset/weak-bobcats-invite.md
- packages/blade/src/components/DatePicker/CalendarHeader.web.tsx
was testing 12.2.0 , 
found this bug. ideal it should be              ```  onLevelChange('year') ``` , instead of                 
``` onLevelChange('month')```
ref - https://github.com/razorpay/blade/pull/2472#discussion_r1916388388
> fix: date picker on level change issue  [FC-1234]

- .changeset/modern-geckos-relate.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
fileUpload component's onRemove behavior clashes with onChange.
I believe onChange should be triggered when onRemove is called, but it should provide the latest value instead of returning outdated values. Currently, we are using onRemove to handle file removal. However, ideally, this should be managed by onChange, similar to how an input's onChange event reflects both the addition and removal of characters in a string.
this pr should go with a major release.
> fix: fileUpload onRemove clashes with onChange [FC-1234]

- .changeset/soft-numbers-divide.md
- packages/blade/src/components/FileUpload/FileUploadItem.tsx
Had a discussion with @~RK. Other actions like preview and delete are center-aligned, so we should center-align the 'Remove File' action while uploading.
Prev - 
Now -
> fix: remove file icon button alignment while uploading

- .changeset/shaggy-cups-marry.md
- packages/blade/codemods/migrate-motion-tokens/transformers/motionTokenMapping.json
- packages/blade/docs/migration-docs/upgrade-v12.md
Missed one token in token mapping of v12 migration script. Added that to codemod and manual migration
> fix(codemod-v12): token mapping in v12 for standard.attentive

- .changeset/sour-cherries-fry.md
- packages/blade/src/utils/types.ts
fix: data analytics attribute from another external module
The problem occurred because interface requires proper name resolution, but type avoids this by inlining the structure. Switching to type fixed the issue because it removed the dependency on DataAnalyticsAttribute being explicitly resolvable across modules.
> fix: data analytics attribute from another external module

- .changeset/nasty-frogs-end.md
- packages/blade/src/components/Avatar/Avatar.web.tsx
- packages/blade/src/components/Menu/docs/Menu.stories.tsx
Ref was missing on one of the if blocks of Avatar which caused Menu to not work
> fix(Avatar): add missing ref on default avatar

- .changeset/serious-nails-hope.md
- packages/blade/src/components/Avatar/Avatar.web.tsx
- packages/blade/src/components/Menu/docs/Menu.stories.tsx
> fix(Avatar): add missing ref on default avatar for v11

- .changeset/moody-coats-clean.md
- packages/blade/src/components/FileUpload/FileUpload.web.tsx
Issue Context: https://razorpay.slack.com/archives/CMQ3RBHEU/p1738568779980839?thread_ts=1738140484.133379&cid=CMQ3RBHEU
Timeline:
In 11.34.1: We did not call `onChange` on removing of file. Only `onRemove` was called
In 11:36.2: We added dispatchEvent call which started calling onChange on onRemove
In 12.4.0: We released a fix thinking onChange call was expected behaviour and we just updated the state value for it
So for consumers upgrading from 11.34.1 -> 12.4.0, it becomes breaking change because onChange was not previously called
Hmm this is wild. So React apparently treats dispatchEvent with input type="text" differently than it treats input type="file"
Reproduction: https://codesandbox.io/p/sandbox/friendly-ishizaka-yk7mm3
I've added more details in issue here - …
> fix(FileUpload): revert to not calling onChange on file remove

- .changeset/itchy-pans-hunt.md
- packages/blade/src/components/SideNav/SideNav.web.tsx
- packages/blade/src/components/SideNav/SideNavBody.web.tsx
- packages/blade/src/components/SideNav/docs/RazorpayLogo.tsx
- packages/blade/src/components/SideNav/docs/SideNav.stories.tsx
- packages/blade/src/components/SideNav/types.ts
> feat: remove overflowY if L1 sidenav is collapsed

- .changeset/twenty-planets-tell.md
- packages/blade/src/components/Input/BaseInput/BaseInput.tsx
- packages/blade/src/components/Input/TextArea/TextArea.stories.tsx
- packages/blade/src/components/Input/TextArea/TextArea.tsx
- add `numberOfLines={1}`
- expose `onKeyDown` on TextArea. 
onKeyDown will be exposed with these arg type-
```
onKeyDown={(args) => 
args.name
args.value
args.event
}
```
Currently other handlers of TextArea expose name and value so it feels inconsistent to have one handler that exposes just event. So using the same type that we internally also use where we append event on top of existing name and value
> feat(TextArea): expose onKeydown on TextArea

- .changeset/eighty-doors-yell.md
- packages/blade/src/components/Input/OTPInput/OTPInput.tsx
- packages/blade/src/components/Input/OTPInput/__tests__/OTPInput.web.test.tsx
In OTPInput, when a value is cleared in one of the input field, persisting the focus in the same input field instead of shifting the focus to previous input field
When user wants to update a particular input field value in OTPInput component, the focus gets shifted to previous input field on clearing the value and user have to shift to the corresponding input field again to enter the updated value
https://github.com/user-attachments/assets/c10a9de6-d959-4d10-8f7b-3d2d19da4965
When `Backspace` or `Delete` key is pressed on an input field in OTPInput component,
- if value existed, then it will be cleared and focus will be persisted on the same input field allowing user to update
- if value is empty, then focus will be shifted to previous input field and its value will be cleared …
> feat: OTPInput field value clear behaviour changes

- .changeset/mean-guests-reflect.md
- packages/blade/src/components/Box/Box.tsx
- packages/blade/src/components/Box/__tests__/Box.native.test.tsx
- packages/blade/src/components/Box/__tests__/Box.web.test.tsx
Remove JS check that was allowing brand colors in box background color
> fix: remove js check that allows brand token for Box backgroundColor

- .changeset/wet-beds-sparkle.md
- packages/blade/src/components/DatePicker/Calendar.web.tsx
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
- packages/blade/src/components/DatePicker/__tests__/DatePicker.test.stories.tsx
[ref](https://razorpay.slack.com/archives/CMQ3RBHEU/p1741088046734839)
> fix(blade): focus on selected date by default in datepicker

- .changeset/polite-crews-accept.md
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
currently date picker have height issue. if month have 4 weeks , it will take less space. and if month have 6 week it will take more space.  due to which height changes and it causes a layout shift.
we have decided  fix its height .
[co-pilot generated summary] 🤖 🌟  - 
This pull request includes a small change to the `DatePicker` component in `packages/blade/src/components/DatePicker/DatePicker.web.tsx`. The change ensures that the height is set only for the day picker, while the year and month pickers will have an automatic height. Additionally, it adds a `justifyContent` property to space the content appropriately.
Changes in `DatePicker` component:
* Set height conditionally for day picker and auto for year/month pickers.
* Added `justifyContent` property to `DatePicker` component.
> fix: date picker height issue

- .changeset/selfish-socks-vanish.md
- packages/blade/src/components/DatePicker/Calendar.web.tsx
- packages/blade/src/components/DatePicker/DatePicker.stories.tsx
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
when we changed date programmatically , date picker does not foucs on selected date. this is because previousDate is not being update. instead of using that we should use controlledValue.
> fix: datepicker autofocus not working when date change programmatically

- packages/blade/src/components/FileUpload/docs/stories.tsx
- packages/blade/src/components/SideNav/docs/SideNav.stories.tsx
- packages/blade/src/components/SideNav/docs/code.ts
- packages/blade/src/components/TopNav/docs/TabNav.stories.tsx
- packages/blade/src/components/TopNav/docs/TopNav.stories.tsx
- packages/blade/src/components/TopNav/docs/code.ts
- packages/blade/src/utils/storybook/Sandbox/StackblitzEditor/Sandbox.web.tsx
We were explicitly defining `.js` extension in some examples. Turned them into `.tsx` so that vite doesn't fail and resolving JSX syntax
> fix(storybook): turn sidenav js examples to tsx

- .changeset/thin-bobcats-invite.md
- packages/blade/src/components/DatePicker/DatePicker.web.tsx
fix: date picker reseting date to prev. value
controlled datepicker was setting value to prevValue if date's value is change programmatically. 
Prev- 
https://github.com/user-attachments/assets/61c17962-43a4-4abf-9135-834cca76643c
Current - 
https://github.com/user-attachments/assets/803caf09-5fd8-4c7f-88a7-5d1005b8b343
> fix: date picker reseting date to prev. value

- .changeset/smooth-peaches-decide.md
- packages/blade/src/components/DatePicker/usePopup.ts
prev - 
The position of the DatePicker changes when switching from the date picker to the year picker.
https://github.com/user-attachments/assets/a16ec32b-668c-4598-b3d2-9c0c2e0effef
now - 
https://github.com/user-attachments/assets/001e0844-7d90-4bf8-9feb-63a4c54b8534
> fix: auto-shifting of the date picker on picker change.

- .changeset/silly-coats-behave.md
- packages/blade/package.json
- packages/blade/src/components/StepGroup/StepLine.web.tsx
- yarn.lock
Removes the `universal-base64` library and adds custom base64 encoding function.
The library used `"browser"` key in package.json which required special handling in bundler. Old projects like admin dashboard don't have setup to handle that and anyways that library was fairly small.
> feat: remove universal-base64 library

- .changeset/curvy-eggs-think.md
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.native.test.tsx.snap
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.web.test.tsx.snap
- packages/blade/src/tokens/theme/createTheme.ts
Updated the create-theme color override util for `disabled` state similar to the ones we have in pre-built `Blade` Theme, as in disabled state the button text looks like in `enabled` mode
- light scheme --> interactive.text.primary.disabled
- light scheme --> interactive.icon.primary.disabled
- dark scheme --> interactive.text.primary.disabled
- dark scheme --> interactive.icon.primary.disabled
For Pre-built Blade Theme, the display state for `disabled` mode is looking as expected and not working only when we use `createTheme` with custom brand color passed
Using `foregroundOnSurface` token for `disabled` state (where button text looks like in `enabled` mode):
Light scheme:
Dark scheme:
Updated token with opacity as we have in pre-built `Blade` Theme for `interactive.[text || …
> feat: createTheme color override changes for disabled state

- .changeset/thirty-rockets-warn.md
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.native.test.tsx.snap
- packages/blade/src/tokens/theme/__tests__/__snapshots__/createTheme.web.test.tsx.snap
- packages/blade/src/tokens/theme/createTheme.ts
- Fixes the `createTheme` util (border color) used to create custom theme for specific brand color
- Updated the logic used by `createTheme` to add the correct override mapping for `surface.border.primary` and `surface.border.muted`
--- 
--- 
---
> fix: createTheme surface primary border color override changes

- .changeset/green-cameras-kneel.md
- packages/blade/src/components/StepGroup/StepItem.stories.tsx
- packages/blade/src/components/StepGroup/StepItem.web.tsx
- packages/blade/src/components/StepGroup/__tests__/StepGroup.web.test.tsx
- packages/blade/src/components/StepGroup/types.ts
The `minWidth` property has been exposed in the `StepItem` component for horizontal orientation. While the `minWidth` prop will be accessible for both vertical and horizontal orientations, it will only be effective in the horizontal orientation.
- Before and after in horizontal orientation.
https://github.com/user-attachments/assets/001b25e8-4fd5-47a1-a712-bd55c18013ca
- Sanity on vertical orientation
https://github.com/user-attachments/assets/16749fd7-f6c7-4c1d-bc68-2c461f9f29a4
Files updated
- packages/blade/src/components/StepGroup/StepItem.stories.tsx
- packages/blade/src/components/StepGroup/StepItem.web.tsx
- packages/blade/src/components/StepGroup/types.ts
- packages/blade/src/components/StepGroup/__tests__/StepGroup.web.test.tsx
> feat: minwidth for stepitem

- .changeset/old-timers-smile.md
- packages/blade/src/components/Form/Selector/SelectorGroupField.tsx
Fix: labelPosition 'top' for CheckboxGroup & RadioGroup on mobile
> fix: label position to 'top' for CheckboxGroup and RadioGroup on mobile viewports

- .changeset/neat-vans-begin.md
- packages/blade/src/components/Table/TableEditableCell.web.tsx
Table Editable Cell seems to take extra width then required. 
issue link - 
https://razorpay.slack.com/archives/CMQ3RBHEU/p1749728867850799 
current behaviour - 
https://github.com/user-attachments/assets/c2bdbac8-3a5d-4e5d-b8ac-733499bd4a9d
after fix in this pr - 
https://github.com/user-attachments/assets/0eb109bf-bd01-4f08-8279-a55aada475ae
more testing - 
https://github.com/user-attachments/assets/c8ca3e2b-f972-4c21-ba13-722a0cbc03c5
Code Sand Box link with this pr - 
https://codesandbox.io/p/sandbox/busy-mayer-gctxgf 
Stack blitz link with master - 
https://stackblitz.com/edit/zz6jnhab-3nwgrw1d?file=App.tsx,package.json
> fix: table editable cell dropdown issue

- packages/blade/.storybook/react/preview.tsx
- packages/blade/src/components/BottomSheet/BottomSheet.web.tsx
- packages/blade/src/components/Table/TableEditableCell.web.tsx
- When `BottomSheet` component was mounted with `isOpen={false}`, the `scrollRef` was not updated with an actual reference to DOM element even after `BottomSheetBody` was rendered into DOM later
- The field margin was not passed with the updated value for `rowDensity` - `comfortable` prop type
- Added `scrollRef` to `useEffect` dependencies array, to update the `lockTarget` with the updated value
- with this, we could avoid passing `null` to `enableBodyScroll` as we will be getting the updated `ref` element even when `BottomSheetBody` component was rendered later
- Consumed `getEditableInputMargin` util which will return the margin for the `Dropdown` element based on `rowDensity` prop
> fix: console error fix for BottomSheet and update margin for TableEditableDropdownCell

- .changeset/many-kings-ring.md
- packages/blade/src/components/Input/BaseInput/__tests__/__snapshots__/BaseInput.web.test.tsx.snap
- packages/blade/src/components/Tooltip/Tooltip.web.tsx
Updated `Tooltip` component to consume `useMergeRefs` instead of `mergeRefs` util
The `mergeRefs` util which is consumed in `Tooltip` component is creating a new ref callback function on every render which is causing infinite update loop and crashing with `Maximum update depth exceeded` error
https://blade.razorpay.com/?path=/story/components-tooltip--default
Updated to consume `useMergeRefs` in `Tooltip` component, which uses `useMemo` hook to memoize the merged ref callback
> fix: ref update for 'Tooltip' component
